export const FISCAL_POLICY_VIOLATION_CODES = {
    FISCAL_SCOPE_REQUIRED: "FISCAL_SCOPE_REQUIRED",
    ACCOUNTING_PERIOD_CLOSED: "ACCOUNTING_PERIOD_CLOSED",
    CPE_IMMUTABLE: "CPE_IMMUTABLE",
    EVIDENCE_REQUIRED: "EVIDENCE_REQUIRED",
    DETERMINISTIC_ENGINE_REQUIRED: "DETERMINISTIC_ENGINE_REQUIRED",
    FISCAL_TOOL_MAPPING_REQUIRED: "FISCAL_TOOL_MAPPING_REQUIRED",
    CRITICAL_SUNAT_IMPACT_DENIED: "CRITICAL_SUNAT_IMPACT_DENIED",
};
//# sourceMappingURL=fiscal-policy.types.js.map