import type { AgentSystem, AgentTier, UnifiedAgentEntry } from "./types";
export declare const AGENT_REGISTRY: readonly [{
    readonly id: "drenyra-orchestrator";
    readonly name: "Drenyra Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier0";
    readonly parentId: null;
    readonly maySpawn: readonly ["drenyra-sdd-orchestrator", "kuntur-sdd-orchestrator"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Mother orchestrator for all Drenyra CLI operations";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "kuntur-sdd-orchestrator";
    readonly name: "Kuntur SDD Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier1";
    readonly parentId: "drenyra-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Kuntur SDD orchestrator — coordinates subsidiary task decomposition";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "drenyra-sdd-orchestrator";
    readonly name: "Drenyra SDD Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier1";
    readonly parentId: "drenyra-orchestrator";
    readonly maySpawn: readonly ["fiscal-command-orchestrator", "ai-swarm-orchestrator", "drenyra-hr-orchestrator"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Drenyra SDD coordinator — decomposes complex tasks into sub-tasks";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "fiscal-command-orchestrator";
    readonly name: "Fiscal Command Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier2";
    readonly parentId: "drenyra-sdd-orchestrator";
    readonly maySpawn: readonly ["fiscal-sunat-agent", "fiscal-ledger-agent", "fiscal-reconcile-agent"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation", "compliance-audit"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Fiscal command orchestrator — coordinates SUNAT, ledger and reconciliation specialists";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "ai-swarm-orchestrator";
    readonly name: "AI Swarm Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier2";
    readonly parentId: "drenyra-sdd-orchestrator";
    readonly maySpawn: readonly ["swarm-codegen-agent", "swarm-test-agent", "swarm-review-agent"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "AI swarm orchestrator — coordinates codegen, test and review agent swarms";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "drenyra-hr-orchestrator";
    readonly name: "Drenyra HR Orchestrator";
    readonly system: "cli-delegation";
    readonly tier: "tier2";
    readonly parentId: "drenyra-sdd-orchestrator";
    readonly maySpawn: readonly ["hr-payroll-agent", "hr-compliance-agent"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["orchestration", "task-delegation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "HR orchestrator — coordinates payroll and HR compliance specialists";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "fiscal-sunat-agent";
    readonly name: "Fiscal SUNAT Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "fiscal-command-orchestrator";
    readonly maySpawn: readonly ["fiscal-sunat-payload-agent"];
    readonly isLeaf: false;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit", "document-processing"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "SUNAT specialist — validates invoices and tax submissions against SUNAT regulations";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "fiscal-sunat-payload-agent";
    readonly name: "Fiscal SUNAT Payload Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3b";
    readonly parentId: "fiscal-sunat-agent";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "document-processing"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "SUNAT payload drafter — prepares and formats SUNAT submission payloads";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "fiscal-ledger-agent";
    readonly name: "Fiscal Ledger Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "fiscal-command-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["ledger-review", "compliance-audit"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Ledger specialist — reviews and validates ledger entries for fiscal compliance";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "fiscal-reconcile-agent";
    readonly name: "Fiscal Reconcile Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "fiscal-command-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["bank-reconciliation", "data-sync"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Reconciliation specialist — matches bank transactions with ledger entries";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "hr-payroll-agent";
    readonly name: "HR Payroll Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "drenyra-hr-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["hr-payroll", "integration"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Payroll specialist — processes payroll calculations and compliance";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "hr-compliance-agent";
    readonly name: "HR Compliance Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "drenyra-hr-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["compliance-audit", "hr-payroll"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "HR compliance specialist — ensures HR operations meet regulatory requirements";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "swarm-codegen-agent";
    readonly name: "Swarm Codegen Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "ai-swarm-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "test-generation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Codegen leaf — generates code scaffolding and boilerplate implementation";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "swarm-test-agent";
    readonly name: "Swarm Test Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "ai-swarm-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["test-generation", "e2e-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Test leaf — generates and runs tests for code changes";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "swarm-review-agent";
    readonly name: "Swarm Review Agent";
    readonly system: "cli-delegation";
    readonly tier: "tier3";
    readonly parentId: "ai-swarm-orchestrator";
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "security-audit"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["cli"];
    readonly drenyraSubagent: null;
    readonly description: "Review leaf — performs code review and security analysis";
    readonly sourcePath: "apps/drenyra-cli/internal/delegation/graph.go";
}, {
    readonly id: "eviden";
    readonly name: "Eviden";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["evidence-tracking", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Eviden";
    readonly description: "Evidence tracking agent — rastrea evidencia fiscal en comprobantes, SIRE, bancos y documentos";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "vigila";
    readonly name: "Vigila";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["risk-analysis", "monitoring"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Vigila";
    readonly description: "Risk monitoring agent — monitorea riesgo tributario, excepciones y umbrales de aprobación";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "traza";
    readonly name: "Traza";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["tracing", "validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Traza";
    readonly description: "Traceability agent — funde fuentes, reglas y razonamiento con TraceId para auditoría";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "regula";
    readonly name: "Regula";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["compliance-audit", "sunat-validation"];
    readonly approvalClass: "financial-controller";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Regula";
    readonly description: "Compliance agent — orquesta adaptación normativa por país mediante country packs";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "revela";
    readonly name: "Revela";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["report-generation", "knowledge-retrieval"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Revela";
    readonly description: "Explanation agent — explica decisiones y hallazgos en lenguaje claro";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "funde";
    readonly name: "Funde";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["integration", "data-sync"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Funde";
    readonly description: "Integration agent — sincroniza ERPs, bancos y fuentes documentales con controles de acceso";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "reporta";
    readonly name: "Reporta";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["report-generation", "risk-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Reporta";
    readonly description: "Prioritization agent — prioriza alertas y tareas críticas con contexto fiscal";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "archiva";
    readonly name: "Archiva";
    readonly system: "drenyra-core";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["evidence-tracking", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "workspace"];
    readonly drenyraSubagent: "Archiva";
    readonly description: "Archive agent — consolida expediente auditable y evidencia versionada para fiscalización";
    readonly sourcePath: "packages/drenyra-core/src/types.ts";
}, {
    readonly id: "cpe-agent";
    readonly name: "CPE Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["document-processing", "validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for CPE comprobante validation";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "sire-agent";
    readonly name: "SIRE Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for SIRE book review and validation";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "ledger-agent";
    readonly name: "Ledger Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["ledger-review", "validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for ledger entry review";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "conciliation-agent";
    readonly name: "Conciliation Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["bank-reconciliation", "data-sync"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for bank and ledger conciliation";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "fiscal-reviewer-agent";
    readonly name: "Fiscal Reviewer Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["compliance-audit", "risk-analysis"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for fiscal review and risk assessment";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "evidence-agent";
    readonly name: "Evidence Agent";
    readonly system: "domain-mock";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["evidence-tracking", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Mock agent for evidence tracking and document linking";
    readonly sourcePath: "packages/domain/src/drenyra/types.ts";
}, {
    readonly id: "sunat-compliance-agent";
    readonly name: "SUNAT Compliance Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit", "document-processing"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api", "batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Validates invoices and transactions against SUNAT 2026 regulations (IGV, RUC, UBL 2.1)";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/sunat-compliance.agent.ts";
}, {
    readonly id: "invoice-processor-agent";
    readonly name: "Invoice Processor Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["invoice-processing", "document-processing", "validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Processes incoming invoices: extraction, validation, and ledger classification";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/invoice-processor.agent.ts";
}, {
    readonly id: "banking-reconciliation-agent";
    readonly name: "Banking Reconciliation Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["bank-reconciliation", "data-sync", "integration"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api", "batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Matches bank statements against accounting entries for reconciliation";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/banking-reconciliation.agent.ts";
}, {
    readonly id: "tax-optimizer-agent";
    readonly name: "Tax Optimizer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["compliance-audit", "risk-analysis", "report-generation"];
    readonly approvalClass: "financial-controller";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Optimizes tax positions while maintaining SUNAT compliance";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/tax-optimizer.agent.ts";
}, {
    readonly id: "financial-analyzer-agent";
    readonly name: "Financial Analyzer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["report-generation", "risk-analysis", "knowledge-retrieval"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web"];
    readonly drenyraSubagent: null;
    readonly description: "Analyzes financial data and generates insights and forecasts";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/financial-analyzer.agent.ts";
}, {
    readonly id: "spot-calculator-agent";
    readonly name: "SPOT Calculator Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Calculates SPOT (Sistema de Pago de Obligaciones Tributarias) detracciones";
    readonly sourcePath: "packages/agent-swarm/src/agents/financial/spot-calculator.agent.ts";
}, {
    readonly id: "security-audit-agent";
    readonly name: "Security Audit Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["security-audit", "code-review"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Performs automated security audits on codebases and dependencies";
    readonly sourcePath: "packages/agent-swarm/src/agents/code-review/security-audit.agent.ts";
}, {
    readonly id: "quality-analyzer-agent";
    readonly name: "Quality Analyzer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "performance-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Analyzes code quality metrics and enforces coding standards";
    readonly sourcePath: "packages/agent-swarm/src/agents/code-review/quality-analyzer.agent.ts";
}, {
    readonly id: "performance-analyzer-agent";
    readonly name: "Performance Analyzer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["performance-analysis", "code-review"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Identifies performance bottlenecks and optimization opportunities";
    readonly sourcePath: "packages/agent-swarm/src/agents/code-review/performance-analyzer.agent.ts";
}, {
    readonly id: "style-checker-agent";
    readonly name: "Style Checker Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "ui-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Enforces coding style consistency and formatting rules";
    readonly sourcePath: "packages/agent-swarm/src/agents/code-review/style-checker.agent.ts";
}, {
    readonly id: "code-generator-agent";
    readonly name: "Code Generator Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "test-generation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "workspace"];
    readonly drenyraSubagent: null;
    readonly description: "Generates code scaffolding, boilerplate, and implementation patterns";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/code-generator.agent.ts";
}, {
    readonly id: "documentation-agent";
    readonly name: "Documentation Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["report-generation", "knowledge-retrieval"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "web"];
    readonly drenyraSubagent: null;
    readonly description: "Generates and maintains documentation, READMEs, and API references";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/documentation.agent.ts";
}, {
    readonly id: "refactoring-agent";
    readonly name: "Refactoring Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["migration", "code-review"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "workspace"];
    readonly drenyraSubagent: null;
    readonly description: "Refactors code to improve structure, readability, and maintainability";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/refactoring.agent.ts";
}, {
    readonly id: "migration-agent";
    readonly name: "Migration Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["migration", "integration", "database-optimization"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Manages schema and data migrations across environments";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/migration.agent.ts";
}, {
    readonly id: "feature-implementer-agent";
    readonly name: "Feature Implementer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "test-generation", "integration"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "workspace"];
    readonly drenyraSubagent: null;
    readonly description: "Implements new features based on requirements and specifications";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/feature-implementer.agent.ts";
}, {
    readonly id: "bug-fixer-agent";
    readonly name: "Bug Fixer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["code-review", "test-generation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "workspace"];
    readonly drenyraSubagent: null;
    readonly description: "Analyzes and fixes bugs with regression test coverage";
    readonly sourcePath: "packages/agent-swarm/src/agents/development/bug-fixer.agent.ts";
}, {
    readonly id: "test-generator-agent";
    readonly name: "Test Generator Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["test-generation", "e2e-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Generates unit, integration, and E2E tests with coverage targets";
    readonly sourcePath: "packages/agent-swarm/src/agents/testing/test-generator.agent.ts";
}, {
    readonly id: "coverage-analyzer-agent";
    readonly name: "Coverage Analyzer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["test-generation", "performance-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Analyzes test coverage gaps and suggests improvements";
    readonly sourcePath: "packages/agent-swarm/src/agents/testing/coverage-analyzer.agent.ts";
}, {
    readonly id: "integration-tester-agent";
    readonly name: "Integration Tester Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["e2e-testing", "integration", "ui-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Tests API and service integrations end-to-end";
    readonly sourcePath: "packages/agent-swarm/src/agents/testing/integration-tester.agent.ts";
}, {
    readonly id: "e2e-tester-agent";
    readonly name: "E2E Tester Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["e2e-testing", "ui-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Runs full end-to-end tests across the application stack";
    readonly sourcePath: "packages/agent-swarm/src/agents/testing/e2e-tester.agent.ts";
}, {
    readonly id: "database-optimizer-agent";
    readonly name: "Database Optimizer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["database-optimization", "performance-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Optimizes database performance, indexes, and query execution";
    readonly sourcePath: "packages/agent-swarm/src/agents/infrastructure/database-optimizer.agent.ts";
}, {
    readonly id: "api-designer-agent";
    readonly name: "API Designer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["api-design", "integration", "schema-validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "web"];
    readonly drenyraSubagent: null;
    readonly description: "Designs RESTful and GraphQL API contracts and schemas";
    readonly sourcePath: "packages/agent-swarm/src/agents/infrastructure/api-designer.agent.ts";
}, {
    readonly id: "dependency-checker-agent";
    readonly name: "Dependency Checker Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["dependency-checking", "security-audit"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Audits dependency trees for security vulnerabilities and outdated packages";
    readonly sourcePath: "packages/agent-swarm/src/agents/infrastructure/dependency-checker.agent.ts";
}, {
    readonly id: "schema-validator-agent";
    readonly name: "Schema Validator Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["schema-validation", "validation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Validates data schemas against defined constraints and formats";
    readonly sourcePath: "packages/agent-swarm/src/agents/infrastructure/schema-validator.agent.ts";
}, {
    readonly id: "cost-optimizer-agent";
    readonly name: "Cost Optimizer Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["cost-optimization", "performance-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Analyzes and optimizes cloud infrastructure costs";
    readonly sourcePath: "packages/agent-swarm/src/agents/infrastructure/cost-optimizer.agent.ts";
}, {
    readonly id: "deployment-agent";
    readonly name: "Deployment Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["deployment", "integration", "monitoring"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "cli", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Manages application deployment and release pipelines";
    readonly sourcePath: "packages/agent-swarm/src/agents/workflow/deployment.agent.ts";
}, {
    readonly id: "monitoring-agent";
    readonly name: "Monitoring Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["monitoring", "notification", "performance-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Monitors system health, metrics, and alert thresholds";
    readonly sourcePath: "packages/agent-swarm/src/agents/workflow/monitoring.agent.ts";
}, {
    readonly id: "notification-agent";
    readonly name: "Notification Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["notification", "approval-workflow"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Sends notifications across channels (email, Slack, in-app)";
    readonly sourcePath: "packages/agent-swarm/src/agents/workflow/notification.agent.ts";
}, {
    readonly id: "report-generator-agent";
    readonly name: "Report Generator Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["report-generation", "data-visualization"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Generates customizable reports from business data";
    readonly sourcePath: "packages/agent-swarm/src/agents/workflow/report-generator.agent.ts";
}, {
    readonly id: "compliance-auditor-agent";
    readonly name: "Compliance Auditor Agent";
    readonly system: "agent-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["compliance-audit", "security-audit", "report-generation"];
    readonly approvalClass: "financial-controller";
    readonly supportedSurfaces: readonly ["api", "batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Audits regulatory compliance across fiscal, data, and security domains";
    readonly sourcePath: "packages/agent-swarm/src/agents/workflow/compliance-auditor.agent.ts";
}, {
    readonly id: "finance-agent";
    readonly name: "Finance Agent";
    readonly system: "api-agents";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["invoice-processing", "bank-reconciliation", "data-sync"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: "Funde";
    readonly description: "Finance operations agent — integración financiera y sincronización";
    readonly sourcePath: "apps/api/src/features/drenyra/agents.ts";
}, {
    readonly id: "operations-agent";
    readonly name: "Operations Agent";
    readonly system: "api-agents";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["integration", "data-sync", "invoice-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: "Vigila";
    readonly description: "Operations agent — ciclo operativo del negocio: clientes, proveedores, inventario";
    readonly sourcePath: "apps/api/src/features/drenyra/agents.ts";
}, {
    readonly id: "compliance-agent";
    readonly name: "Compliance (Fiscal) Agent";
    readonly system: "api-agents";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit", "document-processing"];
    readonly approvalClass: "financial-controller";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: "Regula";
    readonly description: "Compliance agent — ciclo fiscal peruano: SUNAT, IGV, SIRE, CPE, cierre contable";
    readonly sourcePath: "apps/api/src/features/drenyra/agents.ts";
}, {
    readonly id: "system-admin-agent";
    readonly name: "System Admin Agent";
    readonly system: "api-agents";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["integration", "notification", "approval-workflow"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: "Archiva";
    readonly description: "System administration agent — configuración del sistema, usuarios, integraciones";
    readonly sourcePath: "apps/api/src/features/drenyra/agents.ts";
}, {
    readonly id: "reader-agent";
    readonly name: "Reader Agent";
    readonly system: "ai-pipeline";
    readonly tier: "tier3b";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["reading", "ocr", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "OCR multi-modal reader for invoice documents — Gemini Flash instance";
    readonly sourcePath: "packages/ai/src/agents/agents/reader.agent.ts";
}, {
    readonly id: "parser-agent";
    readonly name: "Parser Agent";
    readonly system: "ai-pipeline";
    readonly tier: "tier3b";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["parsing", "xml-parsing", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "XML UBL 2.0/2.1 parser and validator — Gemini Flash instance";
    readonly sourcePath: "packages/ai/src/agents/agents/parser.agent.ts";
}, {
    readonly id: "validator-agent";
    readonly name: "Validator Agent";
    readonly system: "ai-pipeline";
    readonly tier: "tier3b";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["validation", "sunat-validation", "compliance-audit"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "SUNAT 2026 compliance validator and XML generator — Grok adapter";
    readonly sourcePath: "packages/ai/src/agents/agents/validator.agent.ts";
}, {
    readonly id: "arbitrator-agent";
    readonly name: "Arbitrator Agent";
    readonly system: "ai-pipeline";
    readonly tier: "tier3b";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["arbitration", "knowledge-retrieval", "validation"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Multi-agent debate arbitration and conflict resolution — Gemini Pro";
    readonly sourcePath: "packages/ai/src/agents/agents/arbitrator.agent.ts";
}, {
    readonly id: "swarm-evidence-agent";
    readonly name: "Evidence Agent (AI Swarm)";
    readonly system: "ai-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["evidence-tracking", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Document storage and linking for audit trails — pure infrastructure, no LLM";
    readonly sourcePath: "apps/api/src/features/ai-swarm/agents/evidence.agent.ts";
}, {
    readonly id: "swarm-reconciliation-agent";
    readonly name: "Reconciliation Agent (AI Swarm)";
    readonly system: "ai-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["bank-reconciliation", "data-sync", "integration"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: null;
    readonly description: "Bank statement matching with AI reasoning — handles partial payments and complex scenarios";
    readonly sourcePath: "apps/api/src/features/ai-swarm/agents/reconciliation.agent.ts";
}, {
    readonly id: "swarm-sunat-agent";
    readonly name: "SUNAT Agent (AI Swarm)";
    readonly system: "ai-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["sunat-validation", "compliance-audit", "validation"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: null;
    readonly description: "Hybrid rule-based + AI SUNAT compliance validation (RUC, IGV, UBL 2.1, SIRE)";
    readonly sourcePath: "apps/api/src/features/ai-swarm/agents/sunat.agent.ts";
}, {
    readonly id: "swarm-pcge-agent";
    readonly name: "PCGE Agent (AI Swarm)";
    readonly system: "ai-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["ledger-review", "validation", "document-processing"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: null;
    readonly description: "PCGE accounting classification — classifies transactions into Plan Contable General Empresarial accounts";
    readonly sourcePath: "apps/api/src/features/ai-swarm/agents/pcge.agent.ts";
}, {
    readonly id: "swarm-ocr-agent";
    readonly name: "OCR Agent (AI Swarm)";
    readonly system: "ai-swarm";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["ocr", "document-processing", "reading"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api"];
    readonly drenyraSubagent: null;
    readonly description: "Document data extraction from PDF/image invoices using vision models";
    readonly sourcePath: "apps/api/src/features/ai-swarm/agents/ocr.agent.ts";
}, {
    readonly id: "sunat-visual-fallback";
    readonly name: "SUNAT Visual Fallback Subagent";
    readonly system: "sunat-visual";
    readonly tier: "tier3b";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["visual-analysis", "sunat-validation"];
    readonly approvalClass: "supervisor";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "SUNAT visual fallback for CPE validation when primary SUNAT OSE is unreachable";
    readonly sourcePath: "apps/api/src/features/cpe-validator/application/fallback/sunat-visual-subagent.ts";
}, {
    readonly id: "anomaly-detector-agent";
    readonly name: "Anomaly Detector Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["anomaly-detection", "risk-analysis"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Detects anomalous patterns in financial and operational data";
    readonly sourcePath: "packages/agent-swarm/src/agents/ai-ml/anomaly-detector.agent.ts";
}, {
    readonly id: "nlp-processor-agent";
    readonly name: "NLP Processor Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["nlp-processing", "document-processing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "batch"];
    readonly drenyraSubagent: null;
    readonly description: "Natural language processing for document understanding and classification";
    readonly sourcePath: "packages/agent-swarm/src/agents/ai-ml/nlp-processor.agent.ts";
}, {
    readonly id: "data-visualizer-agent";
    readonly name: "Data Visualizer Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["data-visualization", "report-generation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web"];
    readonly drenyraSubagent: null;
    readonly description: "Creates data visualizations and dashboards from business data";
    readonly sourcePath: "packages/agent-swarm/src/agents/data-science/data-visualizer.agent.ts";
}, {
    readonly id: "incident-responder-agent";
    readonly name: "Incident Responder Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["incident-response", "monitoring", "notification"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Automated incident detection, triage, and response coordination";
    readonly sourcePath: "packages/agent-swarm/src/agents/security-ops/incident-responder.agent.ts";
}, {
    readonly id: "threat-detector-agent";
    readonly name: "Threat Detector Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["threat-detection", "security-audit", "monitoring"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Proactive threat detection and vulnerability assessment";
    readonly sourcePath: "packages/agent-swarm/src/agents/security-ops/threat-detector.agent.ts";
}, {
    readonly id: "budget-tracker-agent";
    readonly name: "Budget Tracker Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["budget-tracking", "cost-optimization", "report-generation"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "web"];
    readonly drenyraSubagent: null;
    readonly description: "Tracks budgets, spending, and cost allocation across departments";
    readonly sourcePath: "packages/agent-swarm/src/agents/cost-management/budget-tracker.agent.ts";
}, {
    readonly id: "usability-tester-agent";
    readonly name: "Usability Tester Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["usability-testing", "ui-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Evaluates user interfaces for usability and accessibility compliance";
    readonly sourcePath: "packages/agent-swarm/src/agents/ux-ui/usability-tester.agent.ts";
}, {
    readonly id: "accessibility-checker-agent";
    readonly name: "Accessibility Checker Agent";
    readonly system: "erp";
    readonly tier: "tier3";
    readonly parentId: null;
    readonly maySpawn: readonly [];
    readonly isLeaf: true;
    readonly capabilities: readonly ["accessibility", "ui-testing", "usability-testing"];
    readonly approvalClass: "not-required";
    readonly supportedSurfaces: readonly ["api", "automation"];
    readonly drenyraSubagent: null;
    readonly description: "Audits web interfaces for WCAG compliance and accessibility issues";
    readonly sourcePath: "packages/agent-swarm/src/agents/ux-ui/accessibility-checker.agent.ts";
}];
export type { AgentCapability, AgentSystem, AgentTier, ApprovalClass, SupportedSurface, } from "./types";
export type { UnifiedAgentEntry };
export declare function getAgentById(id: string): UnifiedAgentEntry | undefined;
export declare function getAgentsBySystem(system: AgentSystem): UnifiedAgentEntry[];
export declare function getAgentsByTier(tier: AgentTier): UnifiedAgentEntry[];
export declare function getLeafAgents(): UnifiedAgentEntry[];
export declare function getRootAgents(): UnifiedAgentEntry[];
export declare function getDrenyraSubagents(): UnifiedAgentEntry[];
//# sourceMappingURL=registry.d.ts.map