export const AGENT_TIERS = [
    "tier0",
    "tier1",
    "tier2",
    "tier3",
    "tier3b",
];
export const AGENT_SYSTEMS = [
    "cli-delegation",
    "drenyra-core",
    "domain-mock",
    "agent-swarm",
    "api-agents",
    "ai-pipeline",
    "ai-swarm",
    "erp",
    "sunat-visual",
];
export const AGENT_CAPABILITIES = [
    "document-processing",
    "ocr",
    "xml-parsing",
    "sunat-validation",
    "bank-reconciliation",
    "ledger-review",
    "invoice-processing",
    "compliance-audit",
    "code-review",
    "test-generation",
    "deployment",
    "monitoring",
    "report-generation",
    "risk-analysis",
    "evidence-tracking",
    "tracing",
    "approval-workflow",
    "data-sync",
    "notification",
    "cost-optimization",
    "security-audit",
    "performance-analysis",
    "migration",
    "integration",
    "hr-payroll",
    "ui-testing",
    "e2e-testing",
    "knowledge-retrieval",
    "task-delegation",
    "orchestration",
    "arbitration",
    "validation",
    "parsing",
    "reading",
    "visual-analysis",
    "accessibility",
    "dependency-checking",
    "schema-validation",
    "api-design",
    "database-optimization",
    "anomaly-detection",
    "nlp-processing",
    "data-visualization",
    "backup-management",
    "incident-response",
    "threat-detection",
    "budget-tracking",
    "usability-testing",
    "access-control",
];
export const APPROVAL_CLASSES = [
    "not-required",
    "supervisor",
    "financial-controller",
];
export const SUPPORTED_SURFACES = [
    "api",
    "cli",
    "web",
    "workspace",
    "batch",
    "automation",
];
export function isAgentInTier(entry, tier) {
    return entry.tier === tier;
}
//# sourceMappingURL=types.js.map