import visualSystem from "./arkalythix-visual-system-v1.json";

const px = (value: number) => `${value}px`;
const ms = (value: number) => `${value}ms`;

export const ARKELYTHEX_VISUAL_SYSTEM_V1 = visualSystem;

/**
 * Canonical variable export for UI runtime usage and audits.
 * `index.css` remains the styling source, this object is the code-level mirror.
 */
export const ARKELYTHEX_CSS_VARIABLES = {
	"--color-bg-0": visualSystem.color.bg["0"],
	"--color-bg-1": visualSystem.color.bg["1"],
	"--color-bg-2": visualSystem.color.bg["2"],
	"--color-surface-1": visualSystem.color.surface["1"],
	"--color-surface-2": visualSystem.color.surface["2"],
	"--color-surface-3": visualSystem.color.surface["3"],
	"--color-stroke-1": visualSystem.color.stroke["1"],
	"--color-stroke-2": visualSystem.color.stroke["2"],
	"--color-stroke-3": visualSystem.color.stroke["3"],
	"--color-text-primary": visualSystem.color.text.primary,
	"--color-text-secondary": visualSystem.color.text.secondary,
	"--color-text-muted": visualSystem.color.text.muted,
	"--color-text-disabled": visualSystem.color.text.disabled,
	"--color-text-inverse": visualSystem.color.text.inverse,
	"--color-green-base": visualSystem.color.accent.green.base,
	"--color-green-hover": visualSystem.color.accent.green.hover,
	"--color-green-active": visualSystem.color.accent.green.active,
	"--color-blue-base": visualSystem.color.accent.blue.base,
	"--color-blue-hover": visualSystem.color.accent.blue.hover,
	"--color-blue-active": visualSystem.color.accent.blue.active,
	"--color-steel-base": visualSystem.color.accent.steel.base,
	"--color-steel-hover": visualSystem.color.accent.steel.hover,
	"--color-steel-active": visualSystem.color.accent.steel.active,
	"--color-success": visualSystem.color.state.success,
	"--color-warning": visualSystem.color.state.warning,
	"--color-danger": visualSystem.color.state.danger,
	"--color-info": visualSystem.color.state.info,
	"--color-ai-halo-cyan": visualSystem.color.ai.haloCyan,
	"--color-ai-halo-steel": visualSystem.color.ai.haloSteel,
	"--font-ui": visualSystem.font.family.ui,
	"--font-mono-ui": visualSystem.font.family.mono,
	"--text-xs": px(visualSystem.font.size.xs),
	"--text-sm": px(visualSystem.font.size.sm),
	"--text-md": px(visualSystem.font.size.md),
	"--text-lg": px(visualSystem.font.size.lg),
	"--text-xl": px(visualSystem.font.size.xl),
	"--text-2xl": px(visualSystem.font.size["2xl"]),
	"--text-3xl": px(visualSystem.font.size["3xl"]),
	"--leading-tight": String(visualSystem.font.lineHeight.tight),
	"--leading-snug": String(visualSystem.font.lineHeight.snug),
	"--leading-normal": String(visualSystem.font.lineHeight.normal),
	"--leading-relaxed": String(visualSystem.font.lineHeight.relaxed),
	"--radius-sm": px(visualSystem.radius.sm),
	"--radius-md": px(visualSystem.radius.md),
	"--radius-lg": px(visualSystem.radius.lg),
	"--radius-xl": px(visualSystem.radius.xl),
	"--radius-pill": String(visualSystem.radius.pill),
	"--border-thin": px(visualSystem.border.thin),
	"--border-thick": px(visualSystem.border.thick),
	"--shadow-1": visualSystem.shadow["1"],
	"--shadow-2": visualSystem.shadow["2"],
	"--animate-fast": ms(visualSystem.motion.duration.fast),
	"--animate-normal": ms(visualSystem.motion.duration.normal),
	"--animate-slow": ms(visualSystem.motion.duration.slow),
	"--ease-standard": visualSystem.motion.easing.standard,
	"--ease-enter": visualSystem.motion.easing.enter,
	"--ease-exit": visualSystem.motion.easing.exit,
	"--z-base": String(visualSystem.z.base),
	"--z-sticky": String(visualSystem.z.sticky),
	"--z-dropdown": String(visualSystem.z.dropdown),
	"--z-overlay": String(visualSystem.z.overlay),
	"--z-modal": String(visualSystem.z.modal),
	"--z-toast": String(visualSystem.z.toast),
	"--z-debug": String(visualSystem.z.debug),
	"--height-button-sm": px(visualSystem.button.height.sm),
	"--height-button-md": px(visualSystem.button.height.md),
	"--height-button-lg": px(visualSystem.button.height.lg),
	"--min-height-composer": px(visualSystem.composer.minHeight),
	"--height-panel-header": px(visualSystem.panel.headerHeight),
} as const;

export const ARKELYTHEX_COMPONENT_TOKENS = {
	button: visualSystem.button,
	composer: visualSystem.composer,
	panel: visualSystem.panel,
	chip: visualSystem.chip,
} as const;
