import { ANIMATIONS, MOTION_VARIANTS } from './motion-tokens';
import { BACKDROP_BLUR, COLORS, GLASS_EFFECTS, GRADIENTS, INTERACTIONS } from './visual-tokens';
import { BLUR, BORDER_RADIUS, OPACITY, SHADOWS, SPACING, TRANSITIONS, Z_INDEX } from './core-tokens';
import { DIMENSIONS, TYPOGRAPHY } from './scale-tokens';

export type BorderRadiusToken = keyof typeof BORDER_RADIUS;
export type ShadowToken = keyof typeof SHADOWS;
export type ZIndexToken = keyof typeof Z_INDEX;
export type BlurToken = keyof typeof BLUR;
export type SpacingToken = keyof typeof SPACING;
export type TransitionToken = keyof typeof TRANSITIONS;
export type OpacityToken = keyof typeof OPACITY;
export type GradientToken = keyof typeof GRADIENTS;
export type BackdropBlurToken = keyof typeof BACKDROP_BLUR;
export type GlassEffectToken = keyof typeof GLASS_EFFECTS;
export type AnimationToken = keyof typeof ANIMATIONS;
export type MotionVariantToken = keyof typeof MOTION_VARIANTS;
export type TypographyToken = keyof typeof TYPOGRAPHY;
export type DimensionToken = keyof typeof DIMENSIONS;
export type ColorToken = keyof typeof COLORS;
export type InteractionToken = keyof typeof INTERACTIONS;
