import type { TenantScope } from "@drenyra/domain/scope";
export interface CreateSubmissionInput {
    companyId: string;
    period: string;
    ledgerType: "ventas" | "compras";
    payloadFormat: "txt" | "csv" | "json" | "xml";
    idempotencyKey: string;
    provider: "sunat-api" | "simulation";
    dryRun: boolean;
    createdBy?: string;
    warnings?: unknown;
}
export interface UpdateSubmissionInput {
    status?: string;
    submissionId?: string;
    sunatTicket?: string;
    trackingId?: string;
    sunatStatus?: string;
    sunatCode?: string;
    sunatMessage?: string;
    errors?: unknown;
    warnings?: unknown;
    submittedAt?: Date;
    processedAt?: Date;
    nextRetryAt?: Date;
}
export declare class SireSubmissionRepository {
    create(input: CreateSubmissionInput): Promise<{
        id: string;
        status: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        companyId: string;
        sunatStatus: string | null;
        submittedAt: Date | null;
        sunatTicket: string | null;
        maxRetries: number;
        nextRetryAt: Date | null;
        provider: string;
        period: string;
        processedAt: Date | null;
        errors: unknown;
        warnings: unknown;
        createdBy: string | null;
        attemptNumber: number;
        idempotencyKey: string;
        ledgerType: string;
        payloadFormat: string;
        dryRun: boolean | null;
        submissionId: string | null;
        trackingId: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
    } | undefined>;
    findByIdempotencyKey(scope: TenantScope, idempotencyKey: string): Promise<{
        id: string;
        companyId: string;
        period: string;
        ledgerType: string;
        payloadFormat: string;
        idempotencyKey: string;
        attemptNumber: number;
        maxRetries: number;
        status: string;
        provider: string;
        dryRun: boolean | null;
        submissionId: string | null;
        sunatTicket: string | null;
        trackingId: string | null;
        sunatStatus: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
        errors: unknown;
        warnings: unknown;
        submittedAt: Date | null;
        processedAt: Date | null;
        nextRetryAt: Date | null;
        createdAt: Date | null;
        updatedAt: Date | null;
        createdBy: string | null;
    } | null>;
    update(scope: TenantScope, id: string, input: UpdateSubmissionInput): Promise<{
        id: string;
        companyId: string;
        period: string;
        ledgerType: string;
        payloadFormat: string;
        idempotencyKey: string;
        attemptNumber: number;
        maxRetries: number;
        status: string;
        provider: string;
        dryRun: boolean | null;
        submissionId: string | null;
        sunatTicket: string | null;
        trackingId: string | null;
        sunatStatus: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
        errors: unknown;
        warnings: unknown;
        submittedAt: Date | null;
        processedAt: Date | null;
        nextRetryAt: Date | null;
        createdAt: Date | null;
        updatedAt: Date | null;
        createdBy: string | null;
    } | undefined>;
    getRecentSubmissionCount(companyId: string, windowMinutes?: number): Promise<number>;
    getFailedSubmissionsForRetry(maxAge: Date): Promise<{
        id: string;
        companyId: string;
        period: string;
        ledgerType: string;
        payloadFormat: string;
        idempotencyKey: string;
        attemptNumber: number;
        maxRetries: number;
        status: string;
        provider: string;
        dryRun: boolean | null;
        submissionId: string | null;
        sunatTicket: string | null;
        trackingId: string | null;
        sunatStatus: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
        errors: unknown;
        warnings: unknown;
        submittedAt: Date | null;
        processedAt: Date | null;
        nextRetryAt: Date | null;
        createdAt: Date | null;
        updatedAt: Date | null;
        createdBy: string | null;
    }[]>;
    incrementAttempt(id: string, companyId?: string): Promise<{
        id: string;
        companyId: string;
        period: string;
        ledgerType: string;
        payloadFormat: string;
        idempotencyKey: string;
        attemptNumber: number;
        maxRetries: number;
        status: string;
        provider: string;
        dryRun: boolean | null;
        submissionId: string | null;
        sunatTicket: string | null;
        trackingId: string | null;
        sunatStatus: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
        errors: unknown;
        warnings: unknown;
        submittedAt: Date | null;
        processedAt: Date | null;
        nextRetryAt: Date | null;
        createdAt: Date | null;
        updatedAt: Date | null;
        createdBy: string | null;
    } | undefined>;
    findByCompanyAndPeriod(companyId: string, period: string): Promise<{
        id: string;
        companyId: string;
        period: string;
        ledgerType: string;
        payloadFormat: string;
        idempotencyKey: string;
        attemptNumber: number;
        maxRetries: number;
        status: string;
        provider: string;
        dryRun: boolean | null;
        submissionId: string | null;
        sunatTicket: string | null;
        trackingId: string | null;
        sunatStatus: string | null;
        sunatCode: string | null;
        sunatMessage: string | null;
        errors: unknown;
        warnings: unknown;
        submittedAt: Date | null;
        processedAt: Date | null;
        nextRetryAt: Date | null;
        createdAt: Date | null;
        updatedAt: Date | null;
        createdBy: string | null;
    }[]>;
}
export declare const sireSubmissionRepository: SireSubmissionRepository;
//# sourceMappingURL=sire-submission.repository.d.ts.map