import type { Bill } from './use-bills.types';

export const MOCK_BILLS: Bill[] = [
  { id: 'b1', vendor: { name: 'Ruby Landscape', initials: 'RL' }, amount: 3050, invoiceNumber: '#INV-2024-001', dueDate: '2025-09-20', status: 'review', currency: 'USD', approvers: [] },
  { id: 'b2', vendor: { name: 'Legal Zoom', initials: 'LZ' }, amount: 450, invoiceNumber: '#INV-8892', dueDate: '2025-09-25', status: 'review', currency: 'USD', approvers: [] },
  { id: 'b4', vendor: { name: 'Microsoft Azure', initials: 'MA' }, amount: 2850, invoiceNumber: '#AZURE-2024-045', dueDate: '2025-09-18', status: 'review', currency: 'USD', approvers: [] },
  { id: 'b5', vendor: { name: 'Amazon Web Services', initials: 'AWS' }, amount: 5200, invoiceNumber: '#AWS-9921-001', dueDate: '2025-09-22', status: 'review', currency: 'USD', approvers: [] },

  { id: 'b6', vendor: { name: 'Google Cloud', initials: 'GC' }, amount: 1240.5, invoiceNumber: '#GCP-9921', dueDate: '2025-09-20', status: 'approval', currency: 'USD', approvers: [{ initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b7', vendor: { name: 'Oracle Cloud', initials: 'OC' }, amount: 3800, invoiceNumber: '#ORACLE-2024-089', dueDate: '2025-09-19', status: 'approval', currency: 'USD', approvers: [{ initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b8', vendor: { name: 'Slack Technologies', initials: 'ST' }, amount: 890, invoiceNumber: '#SLACK-ENT-001', dueDate: '2025-09-21', status: 'approval', currency: 'USD', approvers: [{ initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }] },
  { id: 'b9', vendor: { name: 'Zoom Video', initials: 'ZV' }, amount: 1560, invoiceNumber: '#ZOOM-PRO-045', dueDate: '2025-09-23', status: 'approval', currency: 'USD', approvers: [{ initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b10', vendor: { name: 'GitHub', initials: 'GH' }, amount: 480, invoiceNumber: '#GITHUB-TEAM-2024', dueDate: '2025-09-24', status: 'approval', currency: 'USD', approvers: [{ initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },

  { id: 'b11', vendor: { name: 'Telefonica del Peru', initials: 'TP' }, amount: 2850, invoiceNumber: '#TEL-2024-156', dueDate: '2025-09-15', status: 'payment', currency: 'PEN', approvers: [{ initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }, { initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b12', vendor: { name: 'Enel Distribucion', initials: 'ED' }, amount: 1250.75, invoiceNumber: '#ENEL-AGO-2024', dueDate: '2025-09-10', status: 'payment', currency: 'PEN', approvers: [{ initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }, { initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b13', vendor: { name: 'Microsoft Peru', initials: 'MP' }, amount: 3200, invoiceNumber: '#MSFT-PERU-089', dueDate: '2025-09-12', status: 'payment', currency: 'USD', approvers: [{ initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }, { initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }] },
  { id: 'b14', vendor: { name: 'Uber Business', initials: 'UB' }, amount: 450, invoiceNumber: '#UBER-BIZ-SEP-001', dueDate: '2025-09-08', status: 'payment', currency: 'PEN', approvers: [{ initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b15', vendor: { name: 'Servicios de Limpieza', initials: 'SL' }, amount: 890, invoiceNumber: '#LIMPIEZA-SEP-2024', dueDate: '2025-09-05', status: 'payment', currency: 'PEN', approvers: [{ initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }, { initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }, { initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b16', vendor: { name: 'Seguros Generales', initials: 'SG' }, amount: 1800, invoiceNumber: '#SEGUROS-ANUAL-2024', dueDate: '2025-09-14', status: 'payment', currency: 'PEN', approvers: [{ initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }, { initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },

  { id: 'b17', vendor: { name: 'Adobe Creative Cloud', initials: 'AC' }, amount: 2400, invoiceNumber: '#ADOBE-CC-2024', dueDate: '2025-08-15', status: 'paid', currency: 'USD', paidDate: '2025-08-14', approvers: [{ initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }, { initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b18', vendor: { name: 'Notion Labs', initials: 'NL' }, amount: 960, invoiceNumber: '#NOTION-ENTERPRISE', dueDate: '2025-08-20', status: 'paid', currency: 'USD', paidDate: '2025-08-19', approvers: [{ initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }] },
  { id: 'b19', vendor: { name: 'Figma Inc', initials: 'FI' }, amount: 1440, invoiceNumber: '#FIGMA-PRO-TEAM', dueDate: '2025-08-25', status: 'paid', currency: 'USD', paidDate: '2025-08-24', approvers: [{ initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }, { initials: 'JD', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
  { id: 'b20', vendor: { name: 'Stripe Payments', initials: 'SP' }, amount: 285, invoiceNumber: '#STRIPE-FEES-AGO', dueDate: '2025-08-30', status: 'paid', currency: 'USD', paidDate: '2025-08-29', approvers: [{ initials: 'MR', color: 'bg-[var(--premium-success)] text-[var(--premium-success)]' }, { initials: 'AS', color: 'bg-[var(--premium-action-blue)] text-[var(--premium-action-cyan)]' }] },
];
