/**
 * Fiscal Approval — Core Types
 */

/** Possible states of a recommendation. */
export type ApprovalStatus =
	| "pending"
	| "approved"
	| "rejected"
	| "escalated"
	| "timeout";

/** Types of fiscal actions that can be recommended. */
export type AccionFiscal =
	| "contabilizar-igv"
	| "aplicar-detraccion"
	| "declarar-sire"
	| "corregir-factura"
	| "registrar-retencion"
	| "other";

/** A single evidence source backing a recommendation. */
export interface RecommendationSource {
	tipo: string;
	serie: string;
	numero: number;
	monto: number;
	moneda: string;
	cdrHash?: string;
	fecha: string;
}

/** A recommendation generated by a fiscal pipeline. */
export interface Recommendation {
	id: string;
	pipelineRunId: string;
	tipoAccion: AccionFiscal;
	ruc: string;
	periodo: string;
	descripcion: string;
	monto: number;
	moneda: string;
	confianza: number;
	fuentes: RecommendationSource[];
	status: ApprovalStatus;
	creado: string;
	aprobadoPor?: string;
	aprobadoEn?: string;
	motivoRechazo?: string;
}

/** An approval or rejection action by a human. */
export interface ApprovalAction {
	recommendationId: string;
	action: "approve" | "reject";
	userId: string;
	motivo?: string;
	timestamp: string;
}

/** Configuration for the approval gate behavior. */
export interface ApprovalGateConfig {
	timeoutHoras: number;
	escalateAfter: number;
	minConfidence: number;
	maxPendingPerUser: number;
}

/** Default approval gate configuration. */
export const DEFAULT_APPROVAL_GATE_CONFIG: ApprovalGateConfig = {
	timeoutHoras: 24,
	escalateAfter: 12,
	minConfidence: 0.7,
	maxPendingPerUser: 10,
};

/** Status summary for pending approvals. */
export interface ApprovalSummary {
	total: number;
	pending: number;
	approved: number;
	rejected: number;
	escalated: number;
	recommendations: Recommendation[];
}
