-- Migration 0000: Canonical baseline rebuilt from live Postgres 16
-- Generated by scripts/dev/rebuild-db-baseline.sh

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

--
-- Name: arkalythix_security; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA arkalythix_security;--> statement-breakpoint

--
-- Name: SCHEMA arkalythix_security; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA arkalythix_security IS 'Security primitives for tenant-aware PostgreSQL RLS rollout.';--> statement-breakpoint

--
-- Name: btree_gist; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;--> statement-breakpoint

--
-- Name: EXTENSION btree_gist; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION btree_gist IS 'support for indexing common datatypes in GiST';--> statement-breakpoint

--
-- Name: accounting_job_run_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.accounting_job_run_status AS ENUM (
    'QUEUED',
    'RUNNING',
    'AWAITING_APPROVAL',
    'COMPLETED',
    'FAILED',
    'CANCELLED'
);--> statement-breakpoint

--
-- Name: agent_task_priority; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.agent_task_priority AS ENUM (
    'low',
    'medium',
    'high',
    'critical'
);--> statement-breakpoint

--
-- Name: agent_task_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.agent_task_status AS ENUM (
    'idle',
    'running',
    'paused',
    'completed',
    'failed',
    'retrying'
);--> statement-breakpoint

--
-- Name: alert_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.alert_status AS ENUM (
    'pending',
    'confirmed',
    'false_positive',
    'resolved'
);--> statement-breakpoint

--
-- Name: anomaly_severity; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.anomaly_severity AS ENUM (
    'low',
    'medium',
    'high',
    'critical'
);--> statement-breakpoint

--
-- Name: currency; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.currency AS ENUM (
    'PEN',
    'USD',
    'EUR'
);--> statement-breakpoint

--
-- Name: document_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.document_type AS ENUM (
    'FACTURA',
    'BOLETA',
    'NOTA_CREDITO',
    'NOTA_DEBITO',
    'RECIBO_HONORARIOS',
    'TICKET',
    'MOVIMIENTO_BANCARIO'
);--> statement-breakpoint

--
-- Name: invoice_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.invoice_status AS ENUM (
    'DRAFT',
    'SENT',
    'OVERDUE',
    'PAID',
    'CANCELLED'
);--> statement-breakpoint

--
-- Name: sunat_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.sunat_status AS ENUM (
    'DRAFT',
    'SUBMITTED',
    'ACCEPTED',
    'OBSERVED',
    'REJECTED',
    'ANNULLED'
);--> statement-breakpoint

--
-- Name: tax_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tax_type AS ENUM (
    'GRAVADO',
    'EXONERADO',
    'INAFECTO'
);--> statement-breakpoint

--
-- Name: transaction_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transaction_type AS ENUM (
    'INCOME',
    'EXPENSE'
);--> statement-breakpoint

--
-- Name: current_company_id(); Type: FUNCTION; Schema: arkalythix_security; Owner: -
--

CREATE FUNCTION arkalythix_security.current_company_id() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  SELECT NULLIF(current_setting('arkalythix.current_company_id', true), '')::uuid
$$;--> statement-breakpoint

--
-- Name: FUNCTION current_company_id(); Type: COMMENT; Schema: arkalythix_security; Owner: -
--

COMMENT ON FUNCTION arkalythix_security.current_company_id() IS 'Reads the active tenant company UUID from the arkalythix.current_company_id runtime setting.';--> statement-breakpoint

--
-- Name: current_user_id(); Type: FUNCTION; Schema: arkalythix_security; Owner: -
--

CREATE FUNCTION arkalythix_security.current_user_id() RETURNS text
    LANGUAGE sql STABLE
    AS $$
  SELECT NULLIF(current_setting('arkalythix.current_user_id', true), '')
$$;--> statement-breakpoint

--
-- Name: FUNCTION current_user_id(); Type: COMMENT; Schema: arkalythix_security; Owner: -
--

COMMENT ON FUNCTION arkalythix_security.current_user_id() IS 'Reads the active Better Auth user ID from the arkalythix.current_user_id runtime setting.';--> statement-breakpoint

SET default_tablespace = '';--> statement-breakpoint

SET default_table_access_method = heap;--> statement-breakpoint

--
-- Name: accounting_job_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_job_runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    country_code character varying(2) DEFAULT 'pe'::character varying NOT NULL,
    job_id character varying(100) NOT NULL,
    job_title character varying(160) NOT NULL,
    job_category character varying(50) NOT NULL,
    status public.accounting_job_run_status DEFAULT 'QUEUED'::public.accounting_job_run_status NOT NULL,
    approval_required boolean DEFAULT false NOT NULL,
    requested_by uuid,
    approved_by uuid,
    prompt text NOT NULL,
    summary text,
    input_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    result_payload jsonb,
    evidence_payload jsonb,
    started_at timestamp without time zone DEFAULT now() NOT NULL,
    completed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    currency public.currency NOT NULL,
    bank_name character varying(100),
    account_number character varying(50),
    current_balance numeric(12,2) DEFAULT '0'::numeric NOT NULL,
    last_refreshed timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: agent_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_tasks (
    id character varying(100) NOT NULL,
    company_id uuid NOT NULL,
    user_id uuid NOT NULL,
    agent_id character varying(100) NOT NULL,
    agent_name character varying(255) NOT NULL,
    skill_id character varying(100) NOT NULL,
    skill_name character varying(255) NOT NULL,
    input jsonb DEFAULT '{}'::jsonb NOT NULL,
    result jsonb,
    logs jsonb,
    status public.agent_task_status DEFAULT 'idle'::public.agent_task_status NOT NULL,
    priority public.agent_task_priority DEFAULT 'medium'::public.agent_task_priority NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retries integer DEFAULT 3 NOT NULL,
    parent_task_id character varying(100),
    error_message text,
    error_stack text,
    notified_channels jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    next_retry_at timestamp without time zone
);--> statement-breakpoint

--
-- Name: ai_cost_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_cost_events (
    id text NOT NULL,
    organization_id integer,
    agent_type character varying(100) NOT NULL,
    model_used character varying(100) NOT NULL,
    task_id character varying(100),
    prompt_tokens integer DEFAULT 0 NOT NULL,
    completion_tokens integer DEFAULT 0 NOT NULL,
    total_tokens integer DEFAULT 0 NOT NULL,
    cost_usd numeric(12,8) NOT NULL,
    was_blocked boolean DEFAULT false NOT NULL,
    block_reason text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: anomaly_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anomaly_alerts (
    id text NOT NULL,
    organization_id integer NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id text NOT NULL,
    alert_type character varying(100) NOT NULL,
    severity public.anomaly_severity NOT NULL,
    status public.alert_status DEFAULT 'pending'::public.alert_status NOT NULL,
    detector_agent_id character varying(50) NOT NULL,
    detector_confidence numeric(3,2) NOT NULL,
    lector_confidence numeric(3,2),
    lector_reasoning text,
    validador_confidence numeric(3,2),
    validador_reasoning text,
    swarm_consensus_threshold numeric(3,2) DEFAULT 0.82 NOT NULL,
    swarm_consensus_score numeric(3,2),
    is_false_positive boolean DEFAULT false,
    false_positive_reason text,
    resolved_by text,
    resolved_at timestamp without time zone,
    alert_reasoning text NOT NULL,
    alert_context jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: auth_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_accounts (
    id text NOT NULL,
    account_id text NOT NULL,
    provider_id text NOT NULL,
    user_id text NOT NULL,
    access_token text,
    refresh_token text,
    id_token text,
    access_token_expires_at timestamp without time zone,
    refresh_token_expires_at timestamp without time zone,
    scope text,
    password text,
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: auth_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_audit_logs (
    id text NOT NULL,
    user_id text,
    action character varying(50) NOT NULL,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL,
    ip_address text,
    user_agent text,
    details jsonb
);--> statement-breakpoint

--
-- Name: auth_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_sessions (
    id text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    token text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    ip_address text,
    user_agent text,
    user_id text NOT NULL
);--> statement-breakpoint

--
-- Name: auth_user_companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_companies (
    id text NOT NULL,
    user_id text NOT NULL,
    company_id uuid NOT NULL,
    membership_role character varying(50) DEFAULT 'ACCOUNTANT'::character varying NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: auth_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_users (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    image text,
    ruc text DEFAULT ''::text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp without time zone
);--> statement-breakpoint

--
-- Name: COLUMN auth_users.failed_login_attempts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.auth_users.failed_login_attempts IS 'Counter for consecutive failed login attempts. Reset on successful login.';--> statement-breakpoint

--
-- Name: COLUMN auth_users.locked_until; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.auth_users.locked_until IS 'Timestamp until which account is locked due to failed login attempts. NULL = not locked.';--> statement-breakpoint

--
-- Name: auth_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_verifications (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: bank_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    account_name character varying(200) NOT NULL,
    account_number character varying(50) NOT NULL,
    account_type character varying(20) NOT NULL,
    bank_name character varying(100) NOT NULL,
    bank_code character varying(10),
    branch character varying(100),
    currency character varying(3) DEFAULT 'PEN'::character varying NOT NULL,
    current_balance numeric(19,4) DEFAULT '0'::numeric NOT NULL,
    available_balance numeric(19,4),
    is_active boolean DEFAULT true,
    is_default boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: bank_reconciliations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_reconciliations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    account_id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    opening_balance numeric(19,4) NOT NULL,
    closing_balance numeric(19,4) NOT NULL,
    statement_balance numeric(19,4),
    status character varying(20) DEFAULT 'IN_PROGRESS'::character varying,
    difference numeric(19,4),
    notes text,
    created_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    completed_by uuid
);--> statement-breakpoint

--
-- Name: bank_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    account_id uuid NOT NULL,
    transaction_date date NOT NULL,
    description text NOT NULL,
    reference character varying(100),
    type character varying(10) NOT NULL,
    amount numeric(19,4) NOT NULL,
    balance numeric(19,4),
    category character varying(50),
    tags text,
    is_reconciled boolean DEFAULT false,
    reconciled_at timestamp without time zone,
    reconciled_by uuid,
    invoice_id uuid,
    bill_id uuid,
    payment_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    imported_from character varying(50)
);--> statement-breakpoint

--
-- Name: bill_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bill_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    bill_id uuid NOT NULL,
    product_id uuid,
    description character varying(500) NOT NULL,
    quantity numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: bills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bills (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    vendor_id uuid NOT NULL,
    bill_number character varying(50) NOT NULL,
    issue_date timestamp without time zone DEFAULT now() NOT NULL,
    due_date timestamp without time zone NOT NULL,
    currency public.currency DEFAULT 'PEN'::public.currency NOT NULL,
    exchange_rate numeric(10,4) DEFAULT 1.0000 NOT NULL,
    subtotal_amount numeric(12,2) NOT NULL,
    igv_amount numeric(12,2) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    status public.invoice_status DEFAULT 'DRAFT'::public.invoice_status NOT NULL,
    notes text,
    tags jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: business_partners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_partners (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    tax_id character varying(20) NOT NULL,
    legal_name character varying(255) NOT NULL,
    email character varying(255),
    compliance_score integer DEFAULT 100,
    sunat_condition character varying(50) DEFAULT 'HABIDO'::character varying,
    logo_url text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    partner_document_type character varying(10),
    phone character varying(20),
    address text
);--> statement-breakpoint

--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    type public.transaction_type NOT NULL,
    color character varying(20),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: chat_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    "userId" uuid NOT NULL,
    company_id uuid,
    title character varying(255) DEFAULT 'New Chat'::character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    owner_id uuid NOT NULL,
    economic_group_id uuid,
    is_primary boolean DEFAULT false,
    ruc character varying(11) NOT NULL,
    business_name character varying(255) NOT NULL,
    trade_name character varying(255),
    address text,
    logo_url text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    country_code character varying(2) DEFAULT 'pe'::character varying NOT NULL
);--> statement-breakpoint

--
-- Name: customer_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_profiles (
    id uuid NOT NULL,
    credit_limit numeric(19,2) DEFAULT '0'::numeric NOT NULL,
    credit_days integer DEFAULT 30 NOT NULL,
    customer_segment character varying(50) DEFAULT 'RETAIL'::character varying NOT NULL,
    payment_behavior_score integer DEFAULT 100,
    last_purchase_date timestamp without time zone,
    total_purchases numeric(19,2) DEFAULT '0'::numeric,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id text NOT NULL,
    organization_id integer,
    client_id text,
    client_name character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    file_url text NOT NULL,
    file_type character varying(20) NOT NULL,
    file_size integer NOT NULL,
    status character varying(30) DEFAULT 'UPLOADED'::character varying NOT NULL,
    confidence_level character varying(10),
    extracted_data jsonb,
    validated_by text,
    validated_at timestamp without time zone,
    validation_notes text,
    accounting_entry_id text,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL,
    processed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    company_id uuid
);--> statement-breakpoint

--
-- Name: economic_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.economic_groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    owner_id uuid NOT NULL,
    group_name character varying(255) NOT NULL,
    group_code character varying(50) NOT NULL,
    subscription_tier character varying(50) DEFAULT 'PROFESSIONAL'::character varying,
    monthly_fee numeric(10,2) DEFAULT 350.00,
    max_companies integer DEFAULT '-1'::integer,
    default_currency character varying(3) DEFAULT 'PEN'::character varying,
    timezone character varying(50) DEFAULT 'America/Lima'::character varying,
    is_active boolean DEFAULT true,
    trial_ends_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: firm_model_learnings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.firm_model_learnings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    firm_model_id uuid NOT NULL,
    transaction_id uuid,
    proposed_classification text NOT NULL,
    actual_classification text,
    was_approved boolean DEFAULT false,
    correction_reason text,
    confidence numeric(5,2),
    processing_time integer,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: firm_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.firm_models (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    economic_group_id uuid NOT NULL,
    model_name character varying(255) NOT NULL,
    model_type character varying(50) NOT NULL,
    base_model character varying(100) DEFAULT 'gemini-2.0-flash'::character varying,
    temperature numeric(3,2) DEFAULT 0.10,
    training_examples text NOT NULL,
    accuracy numeric(5,2),
    last_trained_at timestamp without time zone,
    custom_rules text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: frontend_telemetry_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.frontend_telemetry_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind character varying(32) NOT NULL,
    name character varying(120),
    path character varying(300),
    value numeric(14,4),
    rating character varying(20),
    message text,
    stack text,
    context jsonb,
    event_timestamp timestamp without time zone NOT NULL,
    received_at timestamp without time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip_address character varying(120)
);--> statement-breakpoint

--
-- Name: inter_company_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inter_company_transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    economic_group_id uuid NOT NULL,
    from_company_id uuid NOT NULL,
    from_transaction_id uuid,
    to_company_id uuid NOT NULL,
    to_transaction_id uuid,
    concept character varying(500) NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'PEN'::character varying,
    tax_type character varying(50) DEFAULT 'GRAVADO'::character varying,
    igv_amount numeric(12,2),
    detraction_amount numeric(12,2),
    detraction_rate numeric(5,2),
    status character varying(50) DEFAULT 'PENDING'::character varying,
    reconciled_at timestamp without time zone,
    spot_pdf_url text,
    spot_reference_number character varying(50),
    notes text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    detraction_profile character varying(30),
    detraction_rule_code character varying(80)
);--> statement-breakpoint

--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    product_id uuid NOT NULL,
    warehouse_id uuid,
    quantity numeric(19,4) DEFAULT '0'::numeric NOT NULL,
    min_stock numeric(19,4),
    max_stock numeric(19,4),
    unit_cost numeric(19,4),
    total_value numeric(19,4),
    last_updated timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: inventory_movements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_movements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    product_id uuid NOT NULL,
    warehouse_id uuid,
    type character varying(20) NOT NULL,
    quantity numeric(19,4) NOT NULL,
    unit_cost numeric(19,4),
    total_cost numeric(19,4),
    reference character varying(100),
    reference_id uuid,
    reference_number character varying(50),
    notes text,
    reason character varying(100),
    created_at timestamp without time zone DEFAULT now(),
    created_by uuid
);--> statement-breakpoint

--
-- Name: invoice_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    invoice_id uuid NOT NULL,
    product_id uuid,
    description character varying(500) NOT NULL,
    quantity numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    tax_type public.tax_type DEFAULT 'GRAVADO'::public.tax_type NOT NULL,
    igv_rate numeric(5,2) DEFAULT 18.00 NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv_amount numeric(12,2) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    customer_id uuid NOT NULL,
    invoice_number character varying(50) NOT NULL,
    series character varying(10) NOT NULL,
    correlative integer NOT NULL,
    issue_date timestamp without time zone DEFAULT now() NOT NULL,
    due_date timestamp without time zone NOT NULL,
    currency public.currency DEFAULT 'PEN'::public.currency NOT NULL,
    exchange_rate numeric(10,4) DEFAULT 1.0000 NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv_amount numeric(12,2) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    status public.invoice_status DEFAULT 'DRAFT'::public.invoice_status NOT NULL,
    sunat_status public.sunat_status DEFAULT 'DRAFT'::public.sunat_status,
    paid_amount numeric(12,2) DEFAULT '0'::numeric NOT NULL,
    balance_due numeric(12,2) NOT NULL,
    paid_date timestamp without time zone,
    xml_url text,
    cdr_url text,
    pdf_url text,
    notes text,
    tags jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    sunat_ticket text
);--> statement-breakpoint

--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    "sessionId" uuid NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: partial_payment_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partial_payment_transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    partial_payment_id uuid NOT NULL,
    transaction_id uuid NOT NULL,
    amount character varying(30) NOT NULL,
    sequence integer NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: partial_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partial_payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    invoice_id uuid NOT NULL,
    total_paid character varying(30) NOT NULL,
    total_due character varying(30) NOT NULL,
    currency character varying(3) DEFAULT 'PEN'::character varying NOT NULL,
    status character varying(20) DEFAULT 'PARTIAL'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone
);--> statement-breakpoint

--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    amount numeric(12,2) NOT NULL,
    payment_method character varying(50) NOT NULL,
    payment_date timestamp without time zone DEFAULT now() NOT NULL,
    reference character varying(255),
    notes text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    sku character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    category character varying(100),
    unit_price numeric(12,2) NOT NULL,
    cost_price numeric(12,2),
    tax_type public.tax_type DEFAULT 'GRAVADO'::public.tax_type NOT NULL,
    unit character varying(20) DEFAULT 'UND'::character varying NOT NULL,
    stock_quantity numeric(12,2) DEFAULT '0'::numeric,
    min_stock numeric(12,2),
    max_stock numeric(12,2),
    image_url text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: retenciones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.retenciones (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    bill_id uuid NOT NULL,
    supplier_ruc character varying(11) NOT NULL,
    base_amount_cents integer NOT NULL,
    retention_amount_cents integer NOT NULL,
    currency character varying(3) DEFAULT 'PEN'::character varying NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    declaration_period character varying(7) NOT NULL,
    sunat_due_date date NOT NULL,
    pdt_reference character varying(50),
    cancellation_reason text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    declared_at timestamp without time zone,
    paid_at timestamp without time zone,
    cancelled_at timestamp without time zone
);--> statement-breakpoint

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: sire_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sire_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    submission_id uuid NOT NULL,
    job_type character varying(50) NOT NULL,
    status character varying(20) DEFAULT 'QUEUED'::character varying NOT NULL,
    attempt_number integer DEFAULT 1 NOT NULL,
    max_attempts integer DEFAULT 3 NOT NULL,
    scheduled_at timestamp without time zone NOT NULL,
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    last_error text,
    error_details jsonb,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: sire_rate_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sire_rate_limits (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    window_start timestamp without time zone NOT NULL,
    window_end timestamp without time zone NOT NULL,
    request_count integer DEFAULT 0 NOT NULL,
    max_requests integer DEFAULT 10 NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: sire_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sire_submissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    period character varying(7) NOT NULL,
    ledger_type character varying(10) NOT NULL,
    payload_format character varying(10) NOT NULL,
    idempotency_key character varying(100) NOT NULL,
    attempt_number integer DEFAULT 1 NOT NULL,
    max_retries integer DEFAULT 3 NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    provider character varying(20) NOT NULL,
    dry_run boolean DEFAULT false,
    submission_id character varying(100),
    sunat_ticket character varying(100),
    tracking_id character varying(100),
    sunat_status character varying(50),
    sunat_code character varying(20),
    sunat_message text,
    errors jsonb,
    warnings jsonb,
    submitted_at timestamp without time zone,
    processed_at timestamp without time zone,
    next_retry_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    created_by uuid
);--> statement-breakpoint

--
-- Name: sunat_knowledge_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sunat_knowledge_chunks (
    id text NOT NULL,
    source text NOT NULL,
    document_type text NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    category text NOT NULL,
    section text,
    effective_date date,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('spanish'::regconfig, ((((((((COALESCE(title, ''::text) || ' '::text) || COALESCE(content, ''::text)) || ' '::text) || COALESCE(category, ''::text)) || ' '::text) || COALESCE(source, ''::text)) || ' '::text) || COALESCE(section, ''::text)))) STORED
);--> statement-breakpoint

--
-- Name: tax_rule_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_rule_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    rule_id uuid NOT NULL,
    rate numeric(10,6),
    threshold_cents integer,
    threshold_currency character varying(3) DEFAULT 'PEN'::character varying NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: tax_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tax_rules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    category character varying(50) NOT NULL,
    sunat_resolution character varying(50),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: transaction_reconciliation_matches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_reconciliation_matches (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    transaction_id uuid NOT NULL,
    document_id uuid NOT NULL,
    document_type character varying(20) NOT NULL,
    match_score integer NOT NULL,
    match_criteria character varying(50) NOT NULL,
    is_partial boolean DEFAULT false,
    partial_sequence integer,
    is_confirmed boolean DEFAULT false,
    confirmed_at timestamp without time zone,
    confirmed_by uuid,
    is_rejected boolean DEFAULT false,
    rejected_at timestamp without time zone,
    rejected_by uuid,
    created_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    partner_id uuid,
    account_id uuid,
    category_id uuid,
    type public.transaction_type NOT NULL,
    document_type public.document_type NOT NULL,
    series character varying(10),
    number character varying(20),
    issue_date timestamp without time zone NOT NULL,
    due_date timestamp without time zone,
    currency public.currency DEFAULT 'PEN'::public.currency NOT NULL,
    exchange_rate numeric(10,3) DEFAULT 1.000 NOT NULL,
    subtotal numeric(12,2) DEFAULT '0'::numeric NOT NULL,
    igv_amount numeric(12,2) DEFAULT '0'::numeric NOT NULL,
    total_amount numeric(12,2) DEFAULT '0'::numeric NOT NULL,
    is_detraction boolean DEFAULT false,
    detraction_amount numeric(12,2),
    status public.sunat_status DEFAULT 'DRAFT'::public.sunat_status,
    notes text,
    tags jsonb,
    xml_url text,
    cdr_url text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(50) DEFAULT 'USER'::character varying NOT NULL,
    company_id uuid,
    avatar_url text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: vendor_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendor_profiles (
    id uuid NOT NULL,
    payment_term_days integer DEFAULT 30 NOT NULL,
    preferred_payment_method character varying(50) DEFAULT 'TRANSFER'::character varying NOT NULL,
    bank_account text,
    purchase_categories jsonb,
    vendor_rating integer DEFAULT 100,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    company_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(50),
    address text,
    city character varying(100),
    country character varying(2) DEFAULT 'PE'::character varying,
    phone character varying(20),
    email character varying(100),
    manager character varying(100),
    is_active boolean DEFAULT true,
    is_default boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);--> statement-breakpoint

--
-- Name: accounting_job_runs accounting_job_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_job_runs
    ADD CONSTRAINT accounting_job_runs_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: agent_tasks agent_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT agent_tasks_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: ai_cost_events ai_cost_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_cost_events
    ADD CONSTRAINT ai_cost_events_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: anomaly_alerts anomaly_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anomaly_alerts
    ADD CONSTRAINT anomaly_alerts_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_accounts auth_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_accounts
    ADD CONSTRAINT auth_accounts_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_audit_logs auth_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_audit_logs
    ADD CONSTRAINT auth_audit_logs_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_sessions auth_sessions_token_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_token_unique UNIQUE (token);--> statement-breakpoint

--
-- Name: auth_user_companies auth_user_companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_companies
    ADD CONSTRAINT auth_user_companies_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_users auth_users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_email_unique UNIQUE (email);--> statement-breakpoint

--
-- Name: auth_users auth_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: auth_verifications auth_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_verifications
    ADD CONSTRAINT auth_verifications_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: bank_accounts bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: bank_reconciliations bank_reconciliations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_reconciliations
    ADD CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: bank_transactions bank_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: bill_items bill_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill_items
    ADD CONSTRAINT bill_items_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: bills bills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bills
    ADD CONSTRAINT bills_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: business_partners business_partners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_partners
    ADD CONSTRAINT business_partners_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: chat_sessions chat_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: companies companies_ruc_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_ruc_unique UNIQUE (ruc);--> statement-breakpoint

--
-- Name: customer_profiles customer_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_profiles
    ADD CONSTRAINT customer_profiles_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: economic_groups economic_groups_group_code_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.economic_groups
    ADD CONSTRAINT economic_groups_group_code_unique UNIQUE (group_code);--> statement-breakpoint

--
-- Name: economic_groups economic_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.economic_groups
    ADD CONSTRAINT economic_groups_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: firm_model_learnings firm_model_learnings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firm_model_learnings
    ADD CONSTRAINT firm_model_learnings_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: firm_models firm_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firm_models
    ADD CONSTRAINT firm_models_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: frontend_telemetry_events frontend_telemetry_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.frontend_telemetry_events
    ADD CONSTRAINT frontend_telemetry_events_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: inter_company_transactions inter_company_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inter_company_transactions
    ADD CONSTRAINT inter_company_transactions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: inventory_movements inventory_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_movements
    ADD CONSTRAINT inventory_movements_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: invoice_items invoice_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: partial_payment_transactions partial_payment_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partial_payment_transactions
    ADD CONSTRAINT partial_payment_transactions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: partial_payments partial_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partial_payments
    ADD CONSTRAINT partial_payments_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: retenciones retenciones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retenciones
    ADD CONSTRAINT retenciones_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: sire_jobs sire_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sire_jobs
    ADD CONSTRAINT sire_jobs_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: sire_rate_limits sire_rate_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sire_rate_limits
    ADD CONSTRAINT sire_rate_limits_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: sire_submissions sire_submissions_idempotency_key_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sire_submissions
    ADD CONSTRAINT sire_submissions_idempotency_key_unique UNIQUE (idempotency_key);--> statement-breakpoint

--
-- Name: sire_submissions sire_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sire_submissions
    ADD CONSTRAINT sire_submissions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: sunat_knowledge_chunks sunat_knowledge_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sunat_knowledge_chunks
    ADD CONSTRAINT sunat_knowledge_chunks_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: tax_rule_versions tax_rule_versions_no_overlap; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rule_versions
    ADD CONSTRAINT tax_rule_versions_no_overlap EXCLUDE USING gist (rule_id WITH =, daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[)'::text) WITH &&);--> statement-breakpoint

--
-- Name: tax_rule_versions tax_rule_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rule_versions
    ADD CONSTRAINT tax_rule_versions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: tax_rules tax_rules_code_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rules
    ADD CONSTRAINT tax_rules_code_unique UNIQUE (code);--> statement-breakpoint

--
-- Name: tax_rules tax_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rules
    ADD CONSTRAINT tax_rules_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: transaction_reconciliation_matches transaction_reconciliation_matches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_reconciliation_matches
    ADD CONSTRAINT transaction_reconciliation_matches_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);--> statement-breakpoint

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: vendor_profiles vendor_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT vendor_profiles_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);--> statement-breakpoint

--
-- Name: accounting_job_runs_company_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_job_runs_company_status_idx ON public.accounting_job_runs USING btree (company_id, status);--> statement-breakpoint

--
-- Name: accounting_job_runs_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_job_runs_created_at_idx ON public.accounting_job_runs USING btree (created_at);--> statement-breakpoint

--
-- Name: accounting_job_runs_job_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounting_job_runs_job_lookup_idx ON public.accounting_job_runs USING btree (company_id, country_code, job_id);--> statement-breakpoint

--
-- Name: agent_task_agent_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_task_agent_id_idx ON public.agent_tasks USING btree (agent_id);--> statement-breakpoint

--
-- Name: agent_task_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_task_company_id_idx ON public.agent_tasks USING btree (company_id);--> statement-breakpoint

--
-- Name: agent_task_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_task_created_at_idx ON public.agent_tasks USING btree (created_at);--> statement-breakpoint

--
-- Name: agent_task_parent_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_task_parent_idx ON public.agent_tasks USING btree (parent_task_id);--> statement-breakpoint

--
-- Name: agent_task_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_task_status_idx ON public.agent_tasks USING btree (status);--> statement-breakpoint

--
-- Name: ai_cost_events_agent_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_cost_events_agent_type_idx ON public.ai_cost_events USING btree (agent_type);--> statement-breakpoint

--
-- Name: ai_cost_events_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_cost_events_created_at_idx ON public.ai_cost_events USING btree (created_at);--> statement-breakpoint

--
-- Name: ai_cost_events_org_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_cost_events_org_id_idx ON public.ai_cost_events USING btree (organization_id);--> statement-breakpoint

--
-- Name: auth_user_companies_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_companies_company_id_idx ON public.auth_user_companies USING btree (company_id);--> statement-breakpoint

--
-- Name: auth_user_companies_user_company_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX auth_user_companies_user_company_uidx ON public.auth_user_companies USING btree (user_id, company_id);--> statement-breakpoint

--
-- Name: auth_user_companies_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_companies_user_id_idx ON public.auth_user_companies USING btree (user_id);--> statement-breakpoint

--
-- Name: bill_company_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bill_company_idx ON public.bills USING btree (company_id);--> statement-breakpoint

--
-- Name: bill_item_bill_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bill_item_bill_idx ON public.bill_items USING btree (bill_id);--> statement-breakpoint

--
-- Name: bill_vendor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bill_vendor_idx ON public.bills USING btree (vendor_id);--> statement-breakpoint

--
-- Name: bp_company_tax_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bp_company_tax_id_idx ON public.business_partners USING btree (company_id, tax_id);--> statement-breakpoint

--
-- Name: createdAt_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "createdAt_idx" ON public.messages USING btree (created_at);--> statement-breakpoint

--
-- Name: customer_profiles_payment_score_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_profiles_payment_score_idx ON public.customer_profiles USING btree (payment_behavior_score);--> statement-breakpoint

--
-- Name: customer_profiles_segment_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_profiles_segment_idx ON public.customer_profiles USING btree (customer_segment);--> statement-breakpoint

--
-- Name: frontend_telemetry_event_ts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX frontend_telemetry_event_ts_idx ON public.frontend_telemetry_events USING btree (event_timestamp);--> statement-breakpoint

--
-- Name: frontend_telemetry_kind_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX frontend_telemetry_kind_idx ON public.frontend_telemetry_events USING btree (kind);--> statement-breakpoint

--
-- Name: frontend_telemetry_path_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX frontend_telemetry_path_idx ON public.frontend_telemetry_events USING btree (path);--> statement-breakpoint

--
-- Name: frontend_telemetry_received_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX frontend_telemetry_received_at_idx ON public.frontend_telemetry_events USING btree (received_at);--> statement-breakpoint

--
-- Name: inter_company_transactions_group_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inter_company_transactions_group_created_at_idx ON public.inter_company_transactions USING btree (economic_group_id, created_at);--> statement-breakpoint

--
-- Name: inter_company_transactions_group_profile_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inter_company_transactions_group_profile_idx ON public.inter_company_transactions USING btree (economic_group_id, detraction_profile);--> statement-breakpoint

--
-- Name: inter_company_transactions_group_rule_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inter_company_transactions_group_rule_idx ON public.inter_company_transactions USING btree (economic_group_id, detraction_rule_code);--> statement-breakpoint

--
-- Name: invoice_company_series_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invoice_company_series_idx ON public.invoices USING btree (company_id, series, correlative);--> statement-breakpoint

--
-- Name: invoice_customer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invoice_customer_idx ON public.invoices USING btree (customer_id);--> statement-breakpoint

--
-- Name: invoice_item_invoice_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invoice_item_invoice_idx ON public.invoice_items USING btree (invoice_id);--> statement-breakpoint

--
-- Name: invoice_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX invoice_status_idx ON public.invoices USING btree (status);--> statement-breakpoint

--
-- Name: payment_company_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_company_idx ON public.payments USING btree (company_id);--> statement-breakpoint

--
-- Name: payment_invoice_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_invoice_idx ON public.payments USING btree (invoice_id);--> statement-breakpoint

--
-- Name: product_company_sku_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX product_company_sku_idx ON public.products USING btree (company_id, sku);--> statement-breakpoint

--
-- Name: retenciones_bill_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX retenciones_bill_idx ON public.retenciones USING btree (bill_id);--> statement-breakpoint

--
-- Name: retenciones_company_period_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX retenciones_company_period_idx ON public.retenciones USING btree (company_id, declaration_period);--> statement-breakpoint

--
-- Name: retenciones_company_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX retenciones_company_status_idx ON public.retenciones USING btree (company_id, status);--> statement-breakpoint

--
-- Name: retenciones_due_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX retenciones_due_date_idx ON public.retenciones USING btree (sunat_due_date);--> statement-breakpoint

--
-- Name: sessionId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "sessionId_idx" ON public.messages USING btree ("sessionId");--> statement-breakpoint

--
-- Name: sunat_knowledge_category_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sunat_knowledge_category_date_idx ON public.sunat_knowledge_chunks USING btree (category, effective_date DESC NULLS LAST);--> statement-breakpoint

--
-- Name: sunat_knowledge_category_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sunat_knowledge_category_idx ON public.sunat_knowledge_chunks USING btree (category);--> statement-breakpoint

--
-- Name: sunat_knowledge_fts_gin_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sunat_knowledge_fts_gin_idx ON public.sunat_knowledge_chunks USING gin (search_vector);--> statement-breakpoint

--
-- Name: sunat_knowledge_source_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sunat_knowledge_source_idx ON public.sunat_knowledge_chunks USING btree (source);--> statement-breakpoint

--
-- Name: tax_rule_versions_effective_window_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tax_rule_versions_effective_window_idx ON public.tax_rule_versions USING btree (effective_from, effective_to);--> statement-breakpoint

--
-- Name: tax_rule_versions_rule_effective_from_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tax_rule_versions_rule_effective_from_idx ON public.tax_rule_versions USING btree (rule_id, effective_from);--> statement-breakpoint

--
-- Name: tax_rules_category_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tax_rules_category_idx ON public.tax_rules USING btree (category);--> statement-breakpoint

--
-- Name: userId_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "userId_idx" ON public.chat_sessions USING btree ("userId");--> statement-breakpoint

--
-- Name: vendor_profiles_rating_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vendor_profiles_rating_idx ON public.vendor_profiles USING btree (vendor_rating);--> statement-breakpoint

--
-- Name: accounting_job_runs accounting_job_runs_approved_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_job_runs
    ADD CONSTRAINT accounting_job_runs_approved_by_users_id_fk FOREIGN KEY (approved_by) REFERENCES public.users(id);--> statement-breakpoint

--
-- Name: accounting_job_runs accounting_job_runs_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_job_runs
    ADD CONSTRAINT accounting_job_runs_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: accounting_job_runs accounting_job_runs_requested_by_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_job_runs
    ADD CONSTRAINT accounting_job_runs_requested_by_users_id_fk FOREIGN KEY (requested_by) REFERENCES public.users(id);--> statement-breakpoint

--
-- Name: accounts accounts_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: agent_tasks agent_tasks_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT agent_tasks_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: agent_tasks agent_tasks_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT agent_tasks_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);--> statement-breakpoint

--
-- Name: auth_accounts auth_accounts_user_id_auth_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_accounts
    ADD CONSTRAINT auth_accounts_user_id_auth_users_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: auth_audit_logs auth_audit_logs_user_id_auth_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_audit_logs
    ADD CONSTRAINT auth_audit_logs_user_id_auth_users_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_users(id);--> statement-breakpoint

--
-- Name: auth_sessions auth_sessions_user_id_auth_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_auth_users_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: auth_user_companies auth_user_companies_user_id_auth_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_companies
    ADD CONSTRAINT auth_user_companies_user_id_auth_users_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: bill_items bill_items_bill_id_bills_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill_items
    ADD CONSTRAINT bill_items_bill_id_bills_id_fk FOREIGN KEY (bill_id) REFERENCES public.bills(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: bill_items bill_items_product_id_products_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill_items
    ADD CONSTRAINT bill_items_product_id_products_id_fk FOREIGN KEY (product_id) REFERENCES public.products(id);--> statement-breakpoint

--
-- Name: bills bills_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bills
    ADD CONSTRAINT bills_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: bills bills_vendor_id_business_partners_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bills
    ADD CONSTRAINT bills_vendor_id_business_partners_id_fk FOREIGN KEY (vendor_id) REFERENCES public.business_partners(id);--> statement-breakpoint

--
-- Name: business_partners business_partners_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_partners
    ADD CONSTRAINT business_partners_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: categories categories_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: chat_sessions chat_sessions_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: chat_sessions chat_sessions_userId_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT "chat_sessions_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: companies companies_owner_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_owner_id_users_id_fk FOREIGN KEY (owner_id) REFERENCES public.users(id);--> statement-breakpoint

--
-- Name: customer_profiles customer_profiles_id_business_partners_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_profiles
    ADD CONSTRAINT customer_profiles_id_business_partners_id_fk FOREIGN KEY (id) REFERENCES public.business_partners(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: firm_model_learnings firm_model_learnings_firm_model_id_firm_models_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firm_model_learnings
    ADD CONSTRAINT firm_model_learnings_firm_model_id_firm_models_id_fk FOREIGN KEY (firm_model_id) REFERENCES public.firm_models(id);--> statement-breakpoint

--
-- Name: firm_models firm_models_economic_group_id_economic_groups_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.firm_models
    ADD CONSTRAINT firm_models_economic_group_id_economic_groups_id_fk FOREIGN KEY (economic_group_id) REFERENCES public.economic_groups(id);--> statement-breakpoint

--
-- Name: inter_company_transactions ict_economic_group_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inter_company_transactions
    ADD CONSTRAINT ict_economic_group_fk FOREIGN KEY (economic_group_id) REFERENCES public.economic_groups(id);--> statement-breakpoint

--
-- Name: invoice_items invoice_items_invoice_id_invoices_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_invoice_id_invoices_id_fk FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: invoice_items invoice_items_product_id_products_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_items
    ADD CONSTRAINT invoice_items_product_id_products_id_fk FOREIGN KEY (product_id) REFERENCES public.products(id);--> statement-breakpoint

--
-- Name: invoices invoices_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: invoices invoices_customer_id_business_partners_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_customer_id_business_partners_id_fk FOREIGN KEY (customer_id) REFERENCES public.business_partners(id);--> statement-breakpoint

--
-- Name: messages messages_sessionId_chat_sessions_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT "messages_sessionId_chat_sessions_id_fk" FOREIGN KEY ("sessionId") REFERENCES public.chat_sessions(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: payments payments_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: payments payments_invoice_id_invoices_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_invoice_id_invoices_id_fk FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: products products_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: sessions sessions_user_id_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id);--> statement-breakpoint

--
-- Name: tax_rule_versions tax_rule_versions_rule_id_tax_rules_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tax_rule_versions
    ADD CONSTRAINT tax_rule_versions_rule_id_tax_rules_id_fk FOREIGN KEY (rule_id) REFERENCES public.tax_rules(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- Name: transactions transactions_account_id_accounts_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_account_id_accounts_id_fk FOREIGN KEY (account_id) REFERENCES public.accounts(id);--> statement-breakpoint

--
-- Name: transactions transactions_category_id_categories_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_category_id_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id);--> statement-breakpoint

--
-- Name: transactions transactions_company_id_companies_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(id);--> statement-breakpoint

--
-- Name: transactions transactions_partner_id_business_partners_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_partner_id_business_partners_id_fk FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);--> statement-breakpoint

--
-- Name: vendor_profiles vendor_profiles_id_business_partners_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT vendor_profiles_id_business_partners_id_fk FOREIGN KEY (id) REFERENCES public.business_partners(id) ON DELETE CASCADE;--> statement-breakpoint

--
-- PostgreSQL database dump complete
--


-- Deferred functions that depend on tables created above
CREATE FUNCTION arkalythix_security.has_company_membership(target_company_id uuid) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'pg_catalog'
    AS $$
  SELECT EXISTS (
    SELECT 1
    FROM auth_user_companies auc
    WHERE auc.company_id = target_company_id
      AND auc.user_id = arkalythix_security.current_user_id()
  )
$$;--> statement-breakpoint

COMMENT ON FUNCTION arkalythix_security.has_company_membership(target_company_id uuid) IS 'Checks whether the current Better Auth user is a member of the target company.';--> statement-breakpoint

CREATE FUNCTION arkalythix_security.has_tenant_access(target_company_id uuid) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public', 'pg_catalog'
    AS $$
  SELECT
    target_company_id IS NOT NULL
    AND arkalythix_security.current_company_id() IS NOT NULL
    AND target_company_id = arkalythix_security.current_company_id()
    AND arkalythix_security.has_company_membership(target_company_id)
$$;--> statement-breakpoint

COMMENT ON FUNCTION arkalythix_security.has_tenant_access(target_company_id uuid) IS 'Checks tenant alignment plus explicit membership for future RLS policies.';--> statement-breakpoint

-- Canonical tenant RLS policies
CREATE SCHEMA IF NOT EXISTS arkalythix_security;--> statement-breakpoint

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.invoices FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS invoices_tenant_guard ON public.invoices;--> statement-breakpoint
CREATE POLICY invoices_tenant_guard
  ON public.invoices
  FOR ALL
  USING (arkalythix_security.has_tenant_access(company_id))
  WITH CHECK (arkalythix_security.has_tenant_access(company_id));--> statement-breakpoint

ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.bills FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS bills_tenant_guard ON public.bills;--> statement-breakpoint
CREATE POLICY bills_tenant_guard
  ON public.bills
  FOR ALL
  USING (arkalythix_security.has_tenant_access(company_id))
  WITH CHECK (arkalythix_security.has_tenant_access(company_id));--> statement-breakpoint

ALTER TABLE public.business_partners ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.business_partners FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS business_partners_tenant_guard ON public.business_partners;--> statement-breakpoint
CREATE POLICY business_partners_tenant_guard
  ON public.business_partners
  FOR ALL
  USING (arkalythix_security.has_tenant_access(company_id))
  WITH CHECK (arkalythix_security.has_tenant_access(company_id));--> statement-breakpoint

ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.bank_accounts FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS bank_accounts_tenant_guard ON public.bank_accounts;--> statement-breakpoint
CREATE POLICY bank_accounts_tenant_guard
  ON public.bank_accounts
  FOR ALL
  USING (arkalythix_security.has_tenant_access(company_id))
  WITH CHECK (arkalythix_security.has_tenant_access(company_id));--> statement-breakpoint

ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.bank_transactions FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS bank_transactions_tenant_guard ON public.bank_transactions;--> statement-breakpoint
CREATE POLICY bank_transactions_tenant_guard
  ON public.bank_transactions
  FOR ALL
  USING (arkalythix_security.has_tenant_access(company_id))
  WITH CHECK (arkalythix_security.has_tenant_access(company_id));--> statement-breakpoint

-- Seed reference data required by taxation rules
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

--
-- Data for Name: tax_rules; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.tax_rules (id, code, name, category, sunat_resolution, created_at) VALUES
	('f5c53716-50c1-4487-8d51-a076e13102a8', 'VAT_TOTAL', 'IGV + IPM total', 'tax', 'LEY-32387', '2026-02-20 10:22:22.666544'),
	('2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 'IGV_COMPONENT', 'Componente IGV', 'tax', 'LEY-32387', '2026-02-20 10:22:22.666544'),
	('b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 'IPM_COMPONENT', 'Componente IPM', 'tax', 'LEY-32387', '2026-02-20 10:22:22.666544'),
	('ae144567-bd8b-4465-874b-1b19edb823c5', 'DETRACCION_SPOT', 'Sistema SPOT detracciones', 'withholding', 'ANEXOS-SPOT', '2026-02-20 10:22:22.666544'),
	('c2887dae-472c-48e6-98c9-f650457f3d40', 'DETRACCION_SPOT_SERVICES', 'SPOT - demas servicios gravados con IGV', 'withholding', 'RS-183-2004/SUNAT', '2026-02-20 10:48:50.184723'),
	('1dced947-b3ca-477f-8800-2f85786bba41', 'DETRACCION_SPOT_TRANSPORT', 'SPOT - transporte de bienes por via terrestre', 'withholding', 'RS-073-2006/SUNAT', '2026-02-20 10:48:50.184723'),
	('1e3561c4-e0b9-4297-a83e-b64a4d0409c9', 'DETRACCION_SPOT_CONSTRUCTION', 'SPOT - contratos de construccion', 'withholding', 'RS-183-2004/SUNAT', '2026-02-20 10:48:50.184723');--> statement-breakpoint

--
-- Data for Name: tax_rule_versions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.tax_rule_versions (id, rule_id, rate, threshold_cents, threshold_currency, effective_from, effective_to, metadata, created_at) VALUES
	('7a8edabb-d37d-4365-b7d4-56fd627d1b41', 'f5c53716-50c1-4487-8d51-a076e13102a8', 0.180000, NULL, 'PEN', '2011-03-01', NULL, '{"legal_basis": "IGV+IPM total"}', '2026-02-20 10:22:22.666544'),
	('fc39f916-ccfb-467d-b0fa-bc64d825dd77', 'ae144567-bd8b-4465-874b-1b19edb823c5', 0.120000, 70000, 'PEN', '2025-01-01', NULL, '{"legal_basis": "SPOT general threshold"}', '2026-02-20 10:22:22.666544'),
	('baabd0bd-5ac0-4058-becb-829e8a98af3a', '2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 0.160000, NULL, 'PEN', '2011-03-01', '2026-01-01', '{"legal_basis": "pre-Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('b077d134-d055-4c96-82ad-78eb7a98b85a', '2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 0.155000, NULL, 'PEN', '2026-01-01', '2027-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('431938c2-8fd8-4ea5-bfd6-22ecc781e7bb', '2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 0.150000, NULL, 'PEN', '2027-01-01', '2028-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('2de862d3-77b9-455d-8c10-2a03f7f4c2a0', '2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 0.145000, NULL, 'PEN', '2028-01-01', '2029-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('06c51c30-31c2-4a4b-925a-bcea29d0f663', '2a8c62bd-ce75-4e90-a83b-bf16d2880b1d', 0.140000, NULL, 'PEN', '2029-01-01', NULL, '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('711afc0e-8252-47df-ba1f-8b6cf241038f', 'b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 0.020000, NULL, 'PEN', '2011-03-01', '2026-01-01', '{"legal_basis": "pre-Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('e591bacb-d01d-48f8-b7bd-6b502d44212e', 'b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 0.025000, NULL, 'PEN', '2026-01-01', '2027-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('3294e122-d82d-4daf-b307-dfbb4f0af4d7', 'b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 0.030000, NULL, 'PEN', '2027-01-01', '2028-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('ef6f734b-24f2-4329-8b40-a30f60701bf5', 'b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 0.035000, NULL, 'PEN', '2028-01-01', '2029-01-01', '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('02514dcc-0f33-4ef6-a609-50b5a0d38e4e', 'b66ff2b5-57e8-411b-a6d4-3128ae0235b3', 0.040000, NULL, 'PEN', '2029-01-01', NULL, '{"legal_basis": "Ley-32387"}', '2026-02-20 10:39:28.208348'),
	('1ac7aa94-3404-4b30-ab34-2dc1375e1a5b', 'c2887dae-472c-48e6-98c9-f650457f3d40', 0.120000, 70000, 'PEN', '2025-01-01', NULL, '{"legal_basis": "SUNAT Anexo 3 - Demas servicios gravados con IGV"}', '2026-02-20 10:48:50.184723'),
	('5533ae83-e35f-4473-adf8-9b7b07321822', '1dced947-b3ca-477f-8800-2f85786bba41', 0.040000, 40000, 'PEN', '2025-01-01', NULL, '{"legal_basis": "SUNAT transporte de bienes por via terrestre"}', '2026-02-20 10:48:50.184723'),
	('8fe8ef7c-da9f-4303-a313-796c4210fa34', '1e3561c4-e0b9-4297-a83e-b64a4d0409c9', 0.040000, 70000, 'PEN', '2025-01-01', NULL, '{"legal_basis": "SUNAT Anexo 3 - Contratos de construccion"}', '2026-02-20 10:48:50.184723');--> statement-breakpoint

--
-- PostgreSQL database dump complete
--
