import {
	ArrowRightLeft,
	BarChart3,
	Briefcase,
	FileSpreadsheet,
	History,
	Landmark,
	Receipt,
	TrendingUp,
} from "lucide-react";
import type { NavigationItem } from "../types";

export const FINANZAS_ITEMS: readonly NavigationItem[] = [
	{
		id: "banking",
		section: "finanzas",
		label: "Bancos y caja",
		description: "Cuentas, movimientos y saldos",
		to: "/tesoreria/banking",
		icon: Landmark,
		keywords: ["bancos", "tesoreria", "cuentas", "saldo"],
	},
	{
		id: "cashflow",
		section: "finanzas",
		label: "Flujo de caja",
		description: "Liquidez y proyeccion inmediata",
		to: "/tesoreria/cashflow",
		icon: TrendingUp,
		keywords: ["cashflow", "flujo", "caja", "liquidez"],
	},
	{
		id: "invoices",
		section: "finanzas",
		label: "Cobros",
		description: "Facturas emitidas y cobranza",
		to: "/facturacion/invoices",
		icon: FileSpreadsheet,
		keywords: ["invoices", "facturas", "cobrar", "ventas"],
	},
	{
		id: "bills",
		section: "finanzas",
		label: "Pagos",
		description: "Facturas recibidas y vencimientos",
		to: "/tesoreria/bills",
		icon: Receipt,
		keywords: ["bills", "pagar", "gastos", "egresos"],
	},
	{
		id: "credit-notes",
		section: "finanzas",
		label: "Notas de crédito",
		description: "Notas de crédito SUNAT y NC",
		to: "/facturacion/credit-notes",
		icon: FileSpreadsheet,
		keywords: ["notas credito", "NC", "anulacion", "descuento", "devolucion", "sunat"],
	},
	{
		id: "debit-notes",
		section: "finanzas",
		label: "Notas de débito",
		description: "Notas de débito SUNAT y ND",
		to: "/facturacion/debit-notes",
		icon: FileSpreadsheet,
		keywords: ["notas debito", "ND", "recargo", "adicional", "sunat"],
	},
	{
		id: "reconciliations",
		section: "finanzas",
		label: "Conciliacion",
		description: "Movimientos por revisar y conciliar",
		to: "/tesoreria/reconciliations",
		icon: ArrowRightLeft,
		keywords: ["conciliacion", "matching", "reconcilia"],
	},
	{
		id: "ledger",
		section: "finanzas",
		label: "Libro mayor",
		description: "Asientos y saldos contables",
		to: "/contabilidad/ledger",
		icon: History,
		keywords: ["ledger", "mayor", "asientos", "pcge"],
	},
	{
		id: "financials",
		section: "finanzas",
		label: "Estados",
		description: "Balance y resultados",
		to: "/contabilidad/financials",
		icon: BarChart3,
		keywords: ["estados", "financieros", "balance", "pyg"],
		showInSidebar: false,
		moduleGroup: "finanzas",
	},
	{
		id: "assets",
		section: "finanzas",
		label: "Activos",
		description: "Activos fijos y depreciacion",
		to: "/contabilidad/assets",
		icon: Briefcase,
		keywords: ["activos", "fijos", "equipos"],
		showInSidebar: false,
		moduleGroup: "finanzas",
	},
];
