import {
	ArrowRightLeft,
	BarChart3,
	Briefcase,
	FileSpreadsheet,
	GitPullRequest,
	History,
} from "lucide-react";
import type { NavigationItem } from "../types";

export const FINANZAS_ITEMS: readonly NavigationItem[] = [
	{
		id: "invoices",
		section: "finanzas",
		label: "Cobros",
		description: "Facturas emitidas y cobranza",
		to: "/facturacion/invoices",
		icon: FileSpreadsheet,
		keywords: ["invoices", "facturas", "cobrar", "ventas"],
	},
	{
		id: "credit-notes",
		section: "finanzas",
		label: "Notas de crédito",
		description: "Notas de crédito SUNAT y NC",
		to: "/facturacion/credit-notes",
		icon: FileSpreadsheet,
		keywords: [
			"notas credito",
			"NC",
			"anulacion",
			"descuento",
			"devolucion",
			"sunat",
		],
	},
	{
		id: "debit-notes",
		section: "finanzas",
		label: "Notas de débito",
		description: "Notas de débito SUNAT y ND",
		to: "/facturacion/debit-notes",
		icon: FileSpreadsheet,
		keywords: ["notas debito", "ND", "recargo", "adicional", "sunat"],
	},
	{
		id: "reconciliations",
		section: "finanzas",
		label: "Conciliacion",
		description: "Movimientos por revisar y conciliar",
		to: "/tesoreria/reconciliations",
		icon: ArrowRightLeft,
		keywords: ["conciliacion", "matching", "reconcilia"],
	},
	{
		id: "ledger",
		section: "finanzas",
		label: "Libro mayor",
		description: "Asientos y saldos contables",
		to: "/contabilidad/ledger",
		icon: History,
		keywords: ["ledger", "mayor", "asientos", "pcge"],
	},
	{
		id: "accounting-pr",
		section: "finanzas",
		label: "Accounting PR",
		description: "Review and approve proposed journal entries before posting",
		to: "/contabilidad/accounting-pr",
		icon: GitPullRequest,
		keywords: [
			"accounting",
			"pr",
			"pull request",
			"propuestas",
			"asientos",
			"mayorizar",
			"aprobacion",
		],
		showInSidebar: false,
		moduleGroup: "finanzas",
	},
	{
		id: "financials",
		section: "finanzas",
		label: "Estados",
		description: "Balance y resultados",
		to: "/contabilidad/financials",
		icon: BarChart3,
		keywords: ["estados", "financieros", "balance", "pyg"],
		showInSidebar: false,
		moduleGroup: "finanzas",
	},
	{
		id: "assets",
		section: "finanzas",
		label: "Activos",
		description: "Activos fijos y depreciacion",
		to: "/contabilidad/assets",
		icon: Briefcase,
		keywords: ["activos", "fijos", "equipos"],
		showInSidebar: false,
		moduleGroup: "finanzas",
	},
];
