import {
	Calculator,
	ClipboardCheck,
	FolderOpen,
	ShieldCheck,
	Scale,
} from "lucide-react";
import type { NavigationItem } from "../types";

export const FISCAL_ITEMS: readonly NavigationItem[] = [
	{
		id: "expedientes",
		section: "compliance",
		label: "Expedientes",
		description: "Dossiers fiscales verificables",
		to: "/cumplimiento/expedientes" as NavigationItem["to"],
		icon: FolderOpen,
		keywords: ["expedientes", "dossier", "documentos", "evidencia"],
		showInSidebar: true,
	},
	{
		id: "approvals",
		section: "compliance",
		label: "Aprobaciones",
		description: "Cola unificada de decisiones",
		to: "/cumplimiento/approvals" as NavigationItem["to"],
		icon: ShieldCheck,
		keywords: ["aprobar", "rechazar", "firma", "revision"],
		showInSidebar: true,
	},
	{
		id: "taxation",
		section: "compliance",
		label: "Impuestos",
		description: "IGV, renta y obligaciones",
		to: "/cumplimiento/taxation" as NavigationItem["to"],
		icon: Scale,
		keywords: ["impuestos", "igv", "renta", "sunat"],
		showInSidebar: false,
	},
	{
		id: "compliance",
		section: "compliance",
		label: "Cumplimiento fiscal",
		description: "Riesgos SUNAT y validaciones",
		to: "/cumplimiento/compliance" as NavigationItem["to"],
		icon: ShieldCheck,
		keywords: ["compliance", "riesgo", "fiscalizacion", "sunat"],
		showInSidebar: false,
	},
	{
		id: "audit",
		section: "compliance",
		label: "Auditoria",
		description: "Control, trazabilidad y hallazgos",
		to: "/cumplimiento/audit" as NavigationItem["to"],
		icon: ClipboardCheck,
		keywords: ["auditoria", "control", "revision"],
		showInSidebar: false,
	},
	{
		id: "reports",
		section: "compliance",
		label: "Reportes",
		description: "Cierres y exportables",
		to: "/contabilidad/reports" as NavigationItem["to"],
		icon: Calculator,
		keywords: ["reportes", "gerencial", "kpi", "exportar"],
		showInSidebar: false,
	},
];
