import {
	Building2,
	PackageSearch,
	ScanLine,
	Tags,
	Zap,
} from "lucide-react";
import type { NavigationItem } from "../types";

export const PLUGINS_ITEMS: readonly NavigationItem[] = [
	{
		id: "plugins-marketplace",
		section: "plugins",
		label: "Marketplace",
		description: "Conectores y módulos instalables",
		to: "/configuracion/plugins",
		icon: Zap,
		keywords: ["plugins", "conectores", "marketplace", "instalar"],
		showInSidebar: true,
	},
	{
		id: "scanner",
		section: "plugins",
		label: "Escanear",
		description: "Escaneo móvil de comprobantes",
		to: "/operaciones/scanner",
		icon: ScanLine,
		keywords: ["scanner", "scan", "captura"],
		showInSidebar: true,
		showInCommandPalette: false,
	},
	{
		id: "inventory",
		section: "plugins",
		label: "Inventario",
		description: "Stock, kardex y movimientos",
		to: "/operaciones/inventory",
		icon: PackageSearch,
		keywords: ["inventario", "stock", "kardex", "almacen"],
		showInSidebar: true,
	},
	{
		id: "products",
		section: "plugins",
		label: "Catálogo",
		description: "Catálogo y clasificación contable",
		to: "/operaciones/products",
		icon: Tags,
		keywords: ["productos", "catalogo", "sku"],
		showInSidebar: true,
	},
	{
		id: "entities",
		section: "plugins",
		label: "Empresas y terceros",
		description: "Directorio fiscal de clientes y proveedores",
		to: "/operaciones/entities",
		icon: Building2,
		keywords: ["entidades", "ruc", "directorio", "partners"],
		showInSidebar: true,
	},
];
