import type { ContributorHealth, RiskItem } from "./types";

export const MOCK_RISKS: RiskItem[] = [
	{
		id: "1",
		category: "fiscal",
		severity: "critical",
		title: "RUC Inactivo - Proveedor Critico",
		description: "3 proveedores tienen RUC inactivo o no habido",
		amount: 45000,
		impact: "Gastos no deducibles",
		probability: 85,
		trend: "up",
	},
	{
		id: "2",
		category: "compliance",
		severity: "high",
		title: "Limite Gastos Representacion",
		description: "92% del limite deducible utilizado",
		amount: 12500,
		impact: "Exceso no deducible: S/ 2,500",
		probability: 70,
		trend: "up",
	},
	{
		id: "3",
		category: "fiscal",
		severity: "high",
		title: "Detracciones Pendientes",
		description: "6 detracciones sin deposito en Banco de la Nacion",
		amount: 4200,
		impact: "Multa 3% del monto",
		probability: 60,
		trend: "stable",
	},
	{
		id: "4",
		category: "operational",
		severity: "medium",
		title: "Concentracion de Proveedores",
		description: "5 proveedores representan el 68% de gastos",
		impact: "Riesgo de dependencia",
		probability: 45,
		trend: "stable",
	},
	{
		id: "5",
		category: "financial",
		severity: "medium",
		title: "Saldo a Favor IGV",
		description: "S/ 12,000 sin aplicar del periodo 2024-12",
		amount: 12000,
		impact: "Flujo de caja afectado",
		probability: 30,
		trend: "down",
	},
	{
		id: "6",
		category: "compliance",
		severity: "low",
		title: "Contratos por Renovar",
		description: "2 contratos de servicios proximos a vencer",
		impact: "Revision de plazos",
		probability: 20,
		trend: "stable",
	},
	{
		id: "7",
		category: "fiscal",
		severity: "critical",
		title: "Facturas con Anomalias",
		description: "3 facturas con montos 45% superiores al promedio",
		amount: 18750,
		impact: "Rectificacion requerida",
		probability: 90,
		trend: "up",
	},
	{
		id: "8",
		category: "operational",
		severity: "low",
		title: "Planilla por Vencer",
		description: "Proximo pago de planilla en 5 dias",
		amount: 45000,
		impact: "Intereses por mora",
		probability: 15,
		trend: "stable",
	},
];

export const MOCK_CONTRIBUTORS: ContributorHealth[] = [
	{
		ruc: "20100123456",
		name: "AWS Peru S.A.C.",
		status: "active",
		riskScore: 5,
		documentsCount: 45,
		totalAmount: 125000,
	},
	{
		ruc: "20501234567",
		name: "Distribuidora Olympia",
		status: "active",
		riskScore: 15,
		documentsCount: 23,
		totalAmount: 45000,
	},
	{
		ruc: "10456789012",
		name: "Servicios Electronicos SA",
		status: "no_habido",
		riskScore: 95,
		documentsCount: 8,
		totalAmount: 22000,
	},
	{
		ruc: "20678901234",
		name: "Transportes Cruz del Sur",
		status: "active",
		riskScore: 8,
		documentsCount: 67,
		totalAmount: 89000,
	},
	{
		ruc: "10345678901",
		name: "Comercializadora del Norte",
		status: "pending",
		riskScore: 45,
		documentsCount: 5,
		totalAmount: 12000,
	},
	{
		ruc: "20123456789",
		name: "Enel Peru S.A.A.",
		status: "active",
		riskScore: 2,
		documentsCount: 12,
		totalAmount: 156000,
	},
];
