import type { Report } from './types';

export const MOCK_REPORTS: Report[] = [
  {
    id: 'r1',
    title: 'ESTADO DE SITUACION FINANCIERA - CONSOLIDADO',
    type: 'BALANCE GENERAL',
    month: 'ENERO',
    year: 2026,
    author: 'ALBERT A.',
    authorInitials: 'AA',
    commentCount: 2,
    coverImage: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&q=80&w=800',
    isPublished: true,
  },
  {
    id: 'r2',
    title: 'ESTADO DE RESULTADOS (POR FUNCION Y NATURALEZA)',
    type: 'ESTADO DE PERDIDAS Y GANANCIAS',
    month: 'ENERO',
    year: 2026,
    author: 'SARAH K.',
    authorInitials: 'SK',
    commentCount: 5,
    coverImage: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=800',
    isPublished: true,
    hasInconsistencies: true,
  },
  {
    id: 'r3',
    title: 'FLUJO DE EFECTIVO - METODO DIRECTO',
    type: 'CONTROL DE LIQUIDEZ',
    month: 'ENERO',
    year: 2026,
    author: 'ALBERT A.',
    authorInitials: 'AA',
    commentCount: 0,
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    isPublished: false,
  },
];
