import { afterEach, describe, expect, it, vi } from "vitest";
import { HttpMissionClient, MissionClientError } from "../index.js";

const snapshot = { id: "mission-1", companyId: "company-1", fiscalPeriod: "2026-03", intent: "monthly-close", status: "DRAFT", version: 1, progress: 0, steps: [], currentStep: "", blockers: [], proposal: null, rejection: null, receiptId: null, receiptHash: null, lastEventSequence: 0, createdAt: "2026-03-01T00:00:00.000Z", updatedAt: "2026-03-01T00:00:00.000Z" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
const client = () => new HttpMissionClient({ baseUrl: "https://api.example.test/", authToken: "token" });

function stream(body: string): Response {
  return new Response(new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode(body)); controller.close(); } }), { headers: { "content-type": "text/event-stream" } });
}

afterEach(() => vi.unstubAllGlobals());

describe("HttpMissionClient", () => {
  it("creates a mission", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(snapshot, 201))); await expect(client().create({ companyId: "company-1", fiscalPeriod: "2026-03", intent: "monthly-close", input: { instruction: "close" } })).resolves.toEqual(snapshot); });
  it("posts creates to the missions collection", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot, 201)); vi.stubGlobal("fetch", fetch); await client().create({ companyId: "company-1", fiscalPeriod: "2026-03", intent: "monthly-close", input: { instruction: "close" } }); expect(fetch).toHaveBeenCalledWith("https://api.example.test/api/v1/missions", expect.objectContaining({ method: "POST" })); });
  it("sends bearer authentication", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot)); vi.stubGlobal("fetch", fetch); await client().get("mission-1"); expect(fetch.mock.calls[0][1].headers).toMatchObject({ Authorization: "Bearer token" }); });
  it("gets a mission", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(snapshot))); await expect(client().get("mission-1")).resolves.toEqual(snapshot); });
  it("URL-encodes mission IDs", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot)); vi.stubGlobal("fetch", fetch); await client().get("mission/a"); expect(fetch.mock.calls[0][0]).toContain("mission%2Fa"); });
  it("lists missions", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json([snapshot]))); await expect(client().list()).resolves.toEqual([snapshot]); });
  it("adds list filters as query parameters", async () => { const fetch = vi.fn().mockResolvedValue(json([])); vi.stubGlobal("fetch", fetch); await client().list({ companyId: "company-1", status: "DRAFT" }); expect(fetch.mock.calls[0][0]).toBe("https://api.example.test/api/v1/missions?companyId=company-1&status=DRAFT"); });
  it("streams snapshots from SSE execute events", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(stream(`data: ${JSON.stringify({ snapshot })}\n\n`))); const received = []; for await (const value of client().execute("mission-1", { expectedMissionVersion: 1 })) received.push(value); expect(received).toEqual([snapshot]); });
  it("ignores SSE comments", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(stream(`:keepalive\n\ndata: ${JSON.stringify({ snapshot })}\n\n`))); const received = []; for await (const value of client().execute("mission-1", { expectedMissionVersion: 1 })) received.push(value); expect(received).toHaveLength(1); });
  it("posts execute command", async () => { const fetch = vi.fn().mockResolvedValue(stream("")); vi.stubGlobal("fetch", fetch); for await (const _ of client().execute("mission-1", { expectedMissionVersion: 2 })) { /* consume */ } expect(fetch).toHaveBeenCalledWith("https://api.example.test/api/v1/missions/mission-1/execute", expect.objectContaining({ method: "POST", body: JSON.stringify({ expectedMissionVersion: 2 }) })); });
  it("approves a proposal", async () => { const result = { receiptId: "receipt-1", receiptHash: "hash", version: 2 }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(result))); await expect(client().approve("mission-1", { proposalId: "proposal-1", proposalVersion: 1, evidenceHash: "hash", expectedMissionVersion: 1 })).resolves.toEqual(result); });
  it("rejects a proposal", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(null, { status: 204 }))); await expect(client().reject("mission-1", { proposalId: "proposal-1", proposalVersion: 1, reason: "Incorrect", expectedMissionVersion: 1 })).resolves.toBeUndefined(); });
  it("reconciles a mission", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json({ ...snapshot, status: "COMPLETED" }))); await expect(client().reconcile("mission-1", { resolution: "COMPLETED", reason: "verified", expectedMissionVersion: 1 })).resolves.toMatchObject({ status: "COMPLETED" }); });
  it("gets readiness gates", async () => { const gates = [{ gateName: "period_open", status: "PASS", details: "open", evaluatedAt: "2026-03-01T00:00:00Z" }]; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(gates))); await expect(client().getGates("mission-1")).resolves.toEqual(gates); });
  it("gets accounting exceptions", async () => { const exceptions = [{ id: "exception-1", missionId: "mission-1", code: "MISSING_EVIDENCE", severity: "warning", subjectRef: "invoice:1", evidenceRefs: [], resolutionStatus: "open" }]; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(exceptions))); await expect(client().getExceptions("mission-1")).resolves.toEqual(exceptions); });
  it("verifies a receipt", async () => { const verification = { valid: true, receiptHash: "hash", computedHash: "hash", missionId: "mission-1" }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json(verification))); await expect(client().verifyReceipt("mission-1")).resolves.toEqual(verification); });
  it("adds an idempotency key to create", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot, 201)); vi.stubGlobal("fetch", fetch); await client().create({ companyId: "company-1", fiscalPeriod: "2026-03", intent: "monthly-close", input: { instruction: "close" } }); expect(fetch.mock.calls[0][1].headers["X-Idempotency-Key"]).toEqual(expect.any(String)); });
  it("adds an idempotency key to approval", async () => { const fetch = vi.fn().mockResolvedValue(json({ receiptId: "receipt-1", receiptHash: "hash", version: 2 })); vi.stubGlobal("fetch", fetch); await client().approve("mission-1", { proposalId: "proposal-1", proposalVersion: 1, evidenceHash: "hash", expectedMissionVersion: 1 }); expect(fetch.mock.calls[0][1].headers["X-Idempotency-Key"]).toEqual(expect.any(String)); });
  it("maps API errors to MissionClientError", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json({ code: "VERSION_CONFLICT", message: "Stale version", details: { current: 2 } }, 409))); await expect(client().get("mission-1")).rejects.toMatchObject({ name: "MissionClientError", code: "VERSION_CONFLICT", statusCode: 409, details: { current: 2 } }); });
  it("uses response status when an API error omits it", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(json({ message: "Missing" }, 404))); await expect(client().get("mission-1")).rejects.toMatchObject({ code: "HTTP_ERROR", statusCode: 404, message: "Missing" }); });
  it("maps malformed error responses", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("unavailable", { status: 503 }))); await expect(client().get("mission-1")).rejects.toBeInstanceOf(MissionClientError); });
  it("preserves custom idempotency keys", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot, 201)); vi.stubGlobal("fetch", fetch); await new HttpMissionClient({ baseUrl: "https://api.example.test", idempotencyKeyFactory: () => "fixed-key" }).create({ companyId: "company-1", fiscalPeriod: "2026-03", intent: "monthly-close", input: { instruction: "close" } }); expect(fetch.mock.calls[0][1].headers["X-Idempotency-Key"]).toBe("fixed-key"); });
  it("does not add auth when no token is configured", async () => { const fetch = vi.fn().mockResolvedValue(json(snapshot)); vi.stubGlobal("fetch", fetch); await new HttpMissionClient({ baseUrl: "https://api.example.test" }).get("mission-1"); expect(fetch.mock.calls[0][1].headers.Authorization).toBeUndefined(); });
  it("rejects execute streams without a body", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(null))); await expect(async () => { for await (const _ of client().execute("mission-1", { expectedMissionVersion: 1 })) { /* consume */ } }).rejects.toMatchObject({ code: "SSE_CONNECTION_LOST" }); });
  it("maps fetch failures to network errors", async () => { vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new TypeError("offline"))); await expect(client().get("mission-1")).rejects.toMatchObject({ code: "NETWORK_ERROR", cause: expect.any(TypeError) }); });
  it("uses the configured retry count", () => { expect(new HttpMissionClient({ baseUrl: "https://api.example.test", maxSseReconnects: 2 })).toBeDefined(); });
});
