import type { DrenyraFiscalWorkInspectEnvelope } from "../api/drenyra-fiscal-work.api";

export function createFiscalWorkInspectSuccessFixture(): DrenyraFiscalWorkInspectEnvelope {
	return {
		status: "success",
		reasonCode: "OK",
		traceId: "trace-inspect-web",
		capabilityId: "drenyra.fiscal-work.inspect",
		evidenceRefs: ["ev-1"],
		sourceSurface: "web",
		data: {
			case: {
				id: "case-1",
				scope: {
					companyId: "company-001",
					companyRuc: "20608451231",
					period: "2026-05",
					countryCode: "PE",
				},
				type: "MONTHLY_CLOSE",
				status: "APPROVAL_PENDING",
				title: "Cierre fiscal mayo",
				description: "Caso de cierre con evidencia",
				riskLevel: "MEDIUM",
				riskScore: 52,
				autonomyLevel: "PREPARE_WITH_APPROVAL",
				createdBy: "user-1",
				createdAt: "2026-05-19T00:00:00.000Z",
				updatedAt: "2026-05-19T00:00:00.000Z",
				metadata: {},
			},
			evidence: [
				{
					id: "ev-1",
					caseId: "case-1",
					scope: {
						companyId: "company-001",
						companyRuc: "20608451231",
						period: "2026-05",
						countryCode: "PE",
					},
					type: "SUNAT_RECORD",
					title: "SIRE",
					summary: "Registro SIRE",
					source: "SUNAT",
					contentHash: "abc",
					addedBy: "user-1",
					createdAt: "2026-05-19T00:00:00.000Z",
					metadata: {},
				},
			],
			agentRuns: [],
			approvals: [
				{
					id: "ap-1",
					caseId: "case-1",
					scope: {
						companyId: "company-001",
						companyRuc: "20608451231",
						period: "2026-05",
						countryCode: "PE",
					},
					status: "PENDING",
					title: "Aprobar preparación",
					description: "Preparar",
					autonomyLevel: "PREPARE_WITH_APPROVAL",
					requestedBy: "user-1",
					requestedAt: "2026-05-19T00:00:00.000Z",
					diff: { before: {}, after: {}, summary: "Preparación" },
					metadata: {},
				},
				{
					id: "ap-2",
					caseId: "case-1",
					scope: {
						companyId: "company-001",
						companyRuc: "20608451231",
						period: "2026-05",
						countryCode: "PE",
					},
					status: "APPROVED",
					title: "Aprobación SIRE previa",
					description: "Validar SIRE",
					autonomyLevel: "PREPARE_WITH_APPROVAL",
					requestedBy: "user-1",
					requestedAt: "2026-05-18T00:00:00.000Z",
					decidedAt: "2026-05-18T01:00:00.000Z",
					decisionReason: "Evidencia SIRE validada",
					diff: { before: {}, after: {}, summary: "Validación previa" },
					metadata: {},
				},
			],
			auditEvents: [
				{
					id: "audit-1",
					scope: {
						companyId: "company-001",
						companyRuc: "20608451231",
						period: "2026-05",
						countryCode: "PE",
					},
					eventType: "FISCAL_CASE_CREATED",
					actorId: "user-1",
					message: "Creado",
					occurredAt: "2026-05-19T00:00:00.000Z",
					metadata: {},
				},
			],
		},
	};
}
