export const DEFAULT_VISIBLE_MONTHS = 6;
export const IGV_RATE = 0.18;

export const DEMO_PARTNERS = [
	{
		key: "customer_anchor",
		taxId: "20614567891",
		legalName: "DISTRIBUCIONES NEBULA RETAIL S.A.C.",
		email: "tesoreria@nebularetail.demo.pe",
	},
	{
		key: "customer_industrial",
		taxId: "20614567892",
		legalName: "CONSTRUCTORA COSTA VERDE INGENIERIA S.A.C.",
		email: "pagos@costaverde.demo.pe",
	},
	{
		key: "customer_food",
		taxId: "20614567893",
		legalName: "ALIMENTOS PACIFICO SUR S.A.C.",
		email: "facturacion@pacificosur.demo.pe",
	},
	{
		key: "vendor_fleet",
		taxId: "20614567901",
		legalName: "SERVICIOS DE FLOTA ANDINA S.A.C.",
		email: "cobranza@flotaandina.demo.pe",
	},
	{
		key: "vendor_energy",
		taxId: "20614567902",
		legalName: "ENERGIA Y SOPORTE LIMA CENTRO S.A.C.",
		email: "facturas@energialc.demo.pe",
	},
	{
		key: "vendor_software",
		taxId: "20614567903",
		legalName: "TECNOLOGIA OPERATIVA DEL PACIFICO S.A.C.",
		email: "cuentas@topacifico.demo.pe",
	},
] as const;

export const DEMO_PRODUCTS = [
	{
		key: "route",
		sku: "LOG-001",
		name: "Servicio de distribucion urbana",
		unitPrice: 4200,
		costPrice: 2550,
		unit: "UND",
	},
	{
		key: "fleet",
		sku: "LOG-002",
		name: "Mantenimiento preventivo de flota",
		unitPrice: 1800,
		costPrice: 980,
		unit: "UND",
	},
	{
		key: "tms",
		sku: "LOG-003",
		name: "Licencia TMS mensual",
		unitPrice: 950,
		costPrice: 310,
		unit: "MES",
	},
	{
		key: "scanner",
		sku: "LOG-004",
		name: "Scanner handheld Zebra TC22",
		unitPrice: 1650,
		costPrice: 1190,
		unit: "UND",
	},
] as const;

export const INVOICE_BLUEPRINTS = [
	{
		correlative: 201,
		monthOffset: -5,
		day: 7,
		subtotal: 12200,
		status: "PAID",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_anchor",
		productKey: "route",
	},
	{
		correlative: 202,
		monthOffset: -4,
		day: 9,
		subtotal: 14800,
		status: "PAID",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_food",
		productKey: "route",
	},
	{
		correlative: 203,
		monthOffset: -3,
		day: 11,
		subtotal: 9800,
		status: "PAID",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_industrial",
		productKey: "tms",
	},
	{
		correlative: 204,
		monthOffset: -2,
		day: 8,
		subtotal: 13200,
		status: "PAID",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_anchor",
		productKey: "fleet",
	},
	{
		correlative: 205,
		monthOffset: -1,
		day: 14,
		subtotal: 16400,
		status: "SENT",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_industrial",
		productKey: "route",
	},
	{
		correlative: 206,
		monthOffset: 0,
		day: 3,
		subtotal: 18400,
		status: "PAID",
		sunatStatus: "ACCEPTED",
		customerKey: "customer_anchor",
		productKey: "route",
	},
	{
		correlative: 207,
		monthOffset: 0,
		day: 9,
		subtotal: 9100,
		status: "SENT",
		sunatStatus: "SUBMITTED",
		customerKey: "customer_food",
		productKey: "tms",
	},
	{
		correlative: 208,
		monthOffset: 0,
		day: 15,
		subtotal: 7600,
		status: "OVERDUE",
		sunatStatus: "REJECTED",
		customerKey: "customer_industrial",
		productKey: "fleet",
	},
	{
		correlative: 209,
		monthOffset: 0,
		day: 21,
		subtotal: 5400,
		status: "DRAFT",
		sunatStatus: null,
		customerKey: "customer_anchor",
		productKey: "scanner",
	},
] as const;

export const BILL_BLUEPRINTS = [
	{
		billNumber: "B001-00003011",
		monthOffset: -1,
		day: 6,
		subtotal: 6200,
		status: "PAID",
		vendorKey: "vendor_fleet",
		productKey: "fleet",
	},
	{
		billNumber: "B001-00003012",
		monthOffset: 0,
		day: 4,
		subtotal: 4100,
		status: "PAID",
		vendorKey: "vendor_energy",
		productKey: "scanner",
	},
	{
		billNumber: "B001-00003013",
		monthOffset: 0,
		day: 12,
		subtotal: 2800,
		status: "SENT",
		vendorKey: "vendor_software",
		productKey: "tms",
	},
	{
		billNumber: "B001-00003014",
		monthOffset: 0,
		day: 18,
		subtotal: 1900,
		status: "DRAFT",
		vendorKey: "vendor_energy",
		productKey: "fleet",
	},
] as const;

export const BANK_TRANSACTION_BLUEPRINTS = [
	{
		monthOffset: -5,
		day: 8,
		type: "CREDIT",
		amount: 14396,
		description: "Cobro factura F001-00000201",
		invoiceIndex: 0,
	},
	{
		monthOffset: -4,
		day: 11,
		type: "CREDIT",
		amount: 17464,
		description: "Cobro factura F001-00000202",
		invoiceIndex: 1,
	},
	{
		monthOffset: -3,
		day: 12,
		type: "DEBIT",
		amount: 7316,
		description: "Pago proveedor mantenimiento",
		billIndex: 0,
	},
	{
		monthOffset: -2,
		day: 9,
		type: "CREDIT",
		amount: 15576,
		description: "Cobro factura F001-00000204",
		invoiceIndex: 3,
	},
	{
		monthOffset: -1,
		day: 15,
		type: "DEBIT",
		amount: 4838,
		description: "Pago energia operativa",
		billIndex: 1,
	},
	{
		monthOffset: 0,
		day: 5,
		type: "CREDIT",
		amount: 21712,
		description: "Cobro factura F001-00000206",
		invoiceIndex: 5,
	},
	{
		monthOffset: 0,
		day: 10,
		type: "DEBIT",
		amount: 3304,
		description: "Pago licencia TMS",
		billIndex: 2,
	},
	{
		monthOffset: 0,
		day: 20,
		type: "DEBIT",
		amount: 2750,
		description: "Pago combustible y peajes",
		billIndex: null,
	},
] as const;
