export { accountingPeriods, accountingPeriodsRelations, cpeLog, cpeLogRelations, detractions, detractionsRelations, exchangeRates, exchangeRatesRelations, journalEntries, journalEntriesRelations, journalEntryLines, journalEntryLinesRelations, pcgeAccounts, pcgeAccountsRelations, } from "./accounting.schema";
export { type AccountingPrStatus, accountingPrs, accountingPrsRelations, type PrSignature, prApprovals, prApprovalsRelations, } from "./accounting-pr.schema";
export { type AgentRunEvent, type AgentRunState, agentRunEvents, agentRunStates, type NewAgentRunEvent, type NewAgentRunState, } from "./agent-run.schema";
export { type AgentRunInput, agentRunInputs, type NewAgentRunInput, } from "./agent-run-inputs.schema";
export { type AgentTask, agentTaskPriorityEnum, agentTaskStatusEnum, agentTasks, agentTasksRelations, type NewAgentTask, } from "./agent-tasks.schema";
export { type AiAgent, type AiTool, type AiToolPermission, type AiTraceEvidence, aiAgents, aiToolPermissions, aiTools, aiTraceEvidence, type NewAiAgent, type NewAiTool, type NewAiToolPermission, type NewAiTraceEvidence, } from "./ai-control-plane.schema";
export { type AiLatencyEvent, aiLatencyEvents, type NewAiLatencyEvent, } from "./ai-latency.schema";
export { type NewUserAISettings, type UserAISettings, userAISettings, } from "./ai-settings.schema";
export type { AIWorkerTask, NewAIWorkerTask, } from "./ai-worker-queues.schema";
export { aiWorkerQueues, aiWorkerQueuesRelations, workerTaskPriorityEnum, workerTaskStatusEnum, } from "./ai-worker-queues.schema";
export { type ConnectionStatus, connectionStatusEnum, type IntegrationCategory, type IntegrationConfigSchema, type IntegrationProvider, integrationCategoryEnum, integrationConnections, integrationConnectionsRelations, integrationProviderEnum, integrationWebhooks, integrationWebhooksRelations, marketplaceIntegrations, marketplaceIntegrationsRelations, } from "./api-marketplace.schema";
export { authAccounts, authAccountsRelations, authAuditLogs, authAuditLogsRelations, authInvitations, authInvitationsRelations, authSessions, authSessionsRelations, authUserCompanies, authUserCompaniesRelations, authUsers, authUsersRelations, authVerifications, } from "./auth.schema";
export { type ActionType, actionTypeEnum, automationExecutions, automationExecutionsRelations, automationSteps, automationStepsRelations, automationWorkflows, automationWorkflowsRelations, type ExecutionStatus, type LastRunStatus, type StepStatus, type StepType, type TriggerType, type WorkflowCategory, type WorkflowStatus, } from "./automation-studio.schema";
export { type AiCostEvent, type AnomalyAlert, aiCostEvents, alertStatusEnum, anomalyAlerts, anomalySeverityEnum, type NewAiCostEvent, type NewAnomalyAlert, type NewSunatKnowledgeChunk, type SunatKnowledgeChunk, sunatKnowledgeChunks, } from "./auxiliary.schema";
export { bankAccounts, bankAccountsRelations, bankReconciliations, bankReconciliationsRelations, bankTransactions, bankTransactionsRelations, } from "./banking.schema";
export { accounts, categories, } from "./banking-core.schema";
export { partialPayments, partialPaymentsRelations, partialPaymentTransactions, partialPaymentTransactionsRelations, reconciliationShadowRunStatusEnum, reconciliationShadowRuns, transactionReconciliationMatches, transactionReconciliationMatchesRelations, } from "./banking-reconciliation-matches.schema";
export { bankProviders } from "./bank-providers.schema";
export { reconciliationRules } from "./reconciliation-rules.schema";
export { pleGenerations, pleGenerationsRelations } from "./ple.schema";
export { type BatchRun, type BatchRunItem, batchRunItems, batchRuns, type NewBatchRun, type NewBatchRunItem, } from "./batch-run.schema";
export { businessPartners, customerProfiles, vendorProfiles, } from "./business-partners.schema";
export { analyticsDashboards, analyticsDashboardsRelations, analyticsReports, analyticsReportsRelations, analyticsWidgets, analyticsWidgetsRelations, type ReportStatus, type ReportType, reportStatusEnum, reportTypeEnum, type WidgetType, widgetTypeEnum, } from "./cfo-analytics.schema";
export { chatSessions, chatSessionsRelations, messages, messagesRelations, } from "./chat.schema";
export { commAutomations, commHistory, commTemplates, } from "./client-comms.schema";
export { accountingJobRuns, companies, organizationMetrics, organizations, sessions, users, } from "./core.schema";
export { type CheckHistoryEntry, checkHistory, type NewCheckHistoryEntry, type NewSystemCheck, type SystemCheck, systemChecks, } from "./doctor-mode.schema";
export { documents } from "./documents.schema";
export { drenyraAgentRuns, drenyraApprovalRequests, drenyraAuditEvents, drenyraEvidenceItems, drenyraFiscalCases, } from "./drenyra-command-center.schema";
export { economicGroups, economicGroupsRelations, firmModelLearnings, firmModelLearningsRelations, firmModels, firmModelsRelations, interCompanyTransactions, interCompanyTransactionsRelations, } from "./economic-groups.schema";
export { accountingJobRunStatusEnum, currencyEnum, documentTypeEnum, invoiceStatusEnum, sunatStatusEnum, taxTypeEnum, transactionTypeEnum, } from "./enums";
export { evidence, evidenceAuditTrail, evidenceAuditTrailRelations, evidenceRelations, evidenceSourceEnum, evidenceStatusEnum, evidenceTypeEnum, } from "./evidence.schema";
export { evidenceLinks, evidenceLinksRelations, } from "./evidence-links.schema";
export { evidenceEdges, evidenceEdgesRelations, evidenceNodes, fiscalReplayCheckpoints, fiscalTruthEvents, fiscalTruthEventsRelations, } from "./fiscal-truth.schema";
export { inventory, inventoryMovements, inventoryMovementsRelations, inventoryRelations, warehouses, } from "./inventory.schema";
export { billItems, billItemsRelations, bills, billsRelations, invoiceItems, invoiceItemsRelations, invoices, invoicesRelations, payments, paymentsRelations, } from "./invoicing.schema";
export { capabilityRoutingRules, modelRegistrations, routingAuditLog, routingAuditLogRelations, } from "./model-router.schema";
export { accountingMissions, accountingMissionsRelations, missionEvents, missionEventsRelations, missionIdempotency, missionLeases, missionLeasesRelations, missionReceipts, missionReceiptsRelations, } from "./mission.schema";
export { type ChecklistCategory, type CloseItemStatus, type CloseStatus, checklistCategoryEnum, closeChecklistItems, closeChecklistItemsRelations, closeChecklists, closeChecklistsRelations, closeGates, closeGatesRelations, closeItemStatusEnum, closeStatusEnum, type GateStatus, type GateType, gateStatusEnum, gateTypeEnum, } from "./monthly-close.schema";
export { platformMcpAuditEvents } from "./platform-mcp.schema";
export { products, productsRelations, } from "./products.schema";
export { accessLogs, failedLoginAttempts, promptGuardAudit, } from "./security.schema";
export { sireJobs, sireJobsRelations, sireRateLimits, sireSubmissions, sireSubmissionsRelations, } from "./sire.schema";
export { sireComparisons, sireDiscrepancyResolutions, } from "./sire-comparisons.schema";
export { companySkills, companySkillsRelations, type InstallationStatus, type SkillCategory, type SkillStatus, skillCapabilities, skillCapabilitiesRelations, skills, skillsRelations, } from "./skills.schema";
export { percepciones, retenciones, taxRules, taxRulesRelations, taxRuleVersions, taxRuleVersionsRelations, } from "./taxation.schema";
export { frontendTelemetryEvents } from "./telemetry.schema";
export { type ThreadAgentRole, threadAgentRoles, threadAgents, threadAgentsRelations, } from "./thread-agents.schema";
export { threadEvidence, threadEvidenceRelations, } from "./thread-evidence.schema";
export { type ThreadTaskStatus, threadTaskStatuses, threadTasks, threadTasksRelations, } from "./thread-tasks.schema";
export { type ThreadEnvironment, type ThreadPriority, type ThreadStatus, threadEnvironments, threadPriorities, threadStatuses, threads, threadsRelations, } from "./threads.schema";
export { transactions, transactionsRelations, } from "./transactions.schema";
export declare const customers: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "business_partners";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        companyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "company_id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        taxId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tax_id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 20;
        }>;
        partnerDocumentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "partner_document_type";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 10;
        }>;
        legalName: import("drizzle-orm/pg-core").PgColumn<{
            name: "legal_name";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        email: import("drizzle-orm/pg-core").PgColumn<{
            name: "email";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        phone: import("drizzle-orm/pg-core").PgColumn<{
            name: "phone";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 20;
        }>;
        address: import("drizzle-orm/pg-core").PgColumn<{
            name: "address";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        complianceScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "compliance_score";
            tableName: "business_partners";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sunatCondition: import("drizzle-orm/pg-core").PgColumn<{
            name: "sunat_condition";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 50;
        }>;
        logoUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "logo_url";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "business_partners";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const vendors: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "business_partners";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        companyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "company_id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        taxId: import("drizzle-orm/pg-core").PgColumn<{
            name: "tax_id";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 20;
        }>;
        partnerDocumentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "partner_document_type";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 10;
        }>;
        legalName: import("drizzle-orm/pg-core").PgColumn<{
            name: "legal_name";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        email: import("drizzle-orm/pg-core").PgColumn<{
            name: "email";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        phone: import("drizzle-orm/pg-core").PgColumn<{
            name: "phone";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 20;
        }>;
        address: import("drizzle-orm/pg-core").PgColumn<{
            name: "address";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        complianceScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "compliance_score";
            tableName: "business_partners";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sunatCondition: import("drizzle-orm/pg-core").PgColumn<{
            name: "sunat_condition";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 50;
        }>;
        logoUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "logo_url";
            tableName: "business_partners";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "business_partners";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const usersRelations: import("drizzle-orm").Relations<"users", {
    companies: import("drizzle-orm").Many<"companies">;
    authSessions: import("drizzle-orm").Many<"sessions">;
    chatSessions: import("drizzle-orm").Many<"chat_sessions">;
}>;
export declare const sessionsRelations: import("drizzle-orm").Relations<"sessions", {
    user: import("drizzle-orm").One<"users", true>;
}>;
export declare const companiesRelations: import("drizzle-orm").Relations<"companies", {
    owner: import("drizzle-orm").One<"users", true>;
    accounts: import("drizzle-orm").Many<"accounts">;
    categories: import("drizzle-orm").Many<"categories">;
    partners: import("drizzle-orm").Many<"business_partners">;
    transactions: import("drizzle-orm").Many<"transactions">;
    products: import("drizzle-orm").Many<"products">;
    invoices: import("drizzle-orm").Many<"invoices">;
}>;
export declare const accountsRelations: import("drizzle-orm").Relations<"accounts", {
    company: import("drizzle-orm").One<"companies", true>;
    transactions: import("drizzle-orm").Many<"transactions">;
}>;
export declare const categoriesRelations: import("drizzle-orm").Relations<"categories", {
    company: import("drizzle-orm").One<"companies", true>;
    transactions: import("drizzle-orm").Many<"transactions">;
}>;
export declare const businessPartnersRelations: import("drizzle-orm").Relations<"business_partners", {
    company: import("drizzle-orm").One<"companies", true>;
    transactions: import("drizzle-orm").Many<"transactions">;
    invoices: import("drizzle-orm").Many<"invoices">;
    bills: import("drizzle-orm").Many<"bills">;
    vendorProfile: import("drizzle-orm").One<"vendor_profiles", true>;
    customerProfile: import("drizzle-orm").One<"customer_profiles", true>;
}>;
export declare const vendorProfilesRelations: import("drizzle-orm").Relations<"vendor_profiles", {
    vendor: import("drizzle-orm").One<"business_partners", true>;
}>;
export declare const customerProfilesRelations: import("drizzle-orm").Relations<"customer_profiles", {
    customer: import("drizzle-orm").One<"business_partners", true>;
}>;
export { type CircuitBreakerState, circuitBreakerStates, type FailedAgentItem, failedAgentItems, type NewCircuitBreakerState, type NewFailedAgentItem, } from "./error-recovery.schema";
export { type ExternalReferenceSource, externalReferences, externalReferencesRelations, } from "./external-references.schema";
export { type FiscalMemoryRevisionRow, type FiscalMemoryRow, fiscalMemories, fiscalMemoryRevisions, type NewFiscalMemoryRevisionRow, type NewFiscalMemoryRow, } from "./fiscal-memory.schema";
export { type IdempotencyRecord, idempotencyRecords, type NewIdempotencyRecord, } from "./idempotency.schema";
export { type AuditReviewStatus, auditFindings, auditFindingsRelations, auditReviewStatuses, auditReviews, auditReviewsRelations, auditRules, auditRulesRelations, type FindingCategory, type FindingSeverity, type FindingStatus, findingCategories, findingSeverities, findingStatuses, } from "./judgment-day.schema";
export { type KbChunk, type KbCollection, type KbDocument, type KbQuery, kbChunks, kbChunksRelations, kbCollections, kbCollectionsRelations, kbDocuments, kbDocumentsRelations, kbQueries, kbQueriesRelations, type NewKbChunk, type NewKbCollection, type NewKbDocument, type NewKbQuery, } from "./rag-enterprise.schema";
//# sourceMappingURL=index.d.ts.map