import { improvementAreas, ImprovementArea } from './improvement-areas';

export interface Proposal {
  title: string;
  body: string;
  areas: ImprovementArea[];
  nextSteps: string[];
}

export function generateProposal(): Proposal {
  const totalIssues = improvementAreas.reduce((sum, area) => sum + area.issues, 0);
  return {
    title: '[auto-sdd] Weekly improvement proposal',
    body: `## Auto-SDD Proposal
This proposal was auto-generated from signal analysis.

### Signal Sources
**Total issues analyzed:** ${totalIssues}
**By label:**
- **merge-health**: 1 issues

**Recent signal issues:**
- #84 **Merge Health — f1fef02** (open)

**Existing OpenSpec proposals:** 67

### Suggested Improvement Areas
Based on recurring signals, consider these improvement areas:
${improvementAreas.map(area => `${area.issues > 0 ? '1. **' + area.name + '** (' + area.issues + ' issues)' : '1. ' + area.name + ' (' + area.issues + ' issues)'}`).join('\n')}

### Next Steps
1. Review this proposal
2. Create an OpenSpec SDD for the prioritized area
3. Update the label to \`status:approved\` when ready

_This issue was auto-generated by the Auto-SDD workflow._`,
    areas: improvementAreas,
    nextSteps: [
      'Review this proposal',
      'Create an OpenSpec SDD for the prioritized area',
      'Update the label to status:approved when ready'
    ]
  };
}
