import type {
	UnifiedAgentEntry,
	AgentTier,
	AgentSystem,
} from "./types";

/**
 * Static compile-time registry of every canonical agent across
 * all Arkelythex / Drenyra systems.
 *
 * This is the SINGLE SOURCE OF TRUTH for agent metadata.
 * Phase 2+ consumers (API endpoint, CLI graph, swarm discovery)
 * will import this array directly.
 */
export const AGENT_REGISTRY = [
	// ═══════════════════════════════════════════════
	// CLI Delegation (apps/drenyra-cli/internal/delegation/graph.go)
	// ═══════════════════════════════════════════════
	{
		id: "arkelythex-orchestrator",
		name: "Arkelythex Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier0" as const,
		parentId: null,
		maySpawn: ["drenyra-sdd-orchestrator", "kuntur-sdd-orchestrator"],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Mother orchestrator for all Drenyra CLI operations",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "kuntur-sdd-orchestrator",
		name: "Kuntur SDD Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier1" as const,
		parentId: "arkelythex-orchestrator",
		maySpawn: [],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Kuntur SDD orchestrator — coordinates subsidiary task decomposition",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "drenyra-sdd-orchestrator",
		name: "Drenyra SDD Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier1" as const,
		parentId: "arkelythex-orchestrator",
		maySpawn: ["fiscal-command-orchestrator", "ai-swarm-orchestrator", "drenyra-hr-orchestrator"],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Drenyra SDD coordinator — decomposes complex tasks into sub-tasks",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "fiscal-command-orchestrator",
		name: "Fiscal Command Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier2" as const,
		parentId: "drenyra-sdd-orchestrator",
		maySpawn: ["fiscal-sunat-agent", "fiscal-ledger-agent", "fiscal-reconcile-agent"],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation", "compliance-audit"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Fiscal command orchestrator — coordinates SUNAT, ledger and reconciliation specialists",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "ai-swarm-orchestrator",
		name: "AI Swarm Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier2" as const,
		parentId: "drenyra-sdd-orchestrator",
		maySpawn: ["swarm-codegen-agent", "swarm-test-agent", "swarm-review-agent"],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "AI swarm orchestrator — coordinates codegen, test and review agent swarms",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "drenyra-hr-orchestrator",
		name: "Drenyra HR Orchestrator",
		system: "cli-delegation" as const,
		tier: "tier2" as const,
		parentId: "drenyra-sdd-orchestrator",
		maySpawn: ["hr-payroll-agent", "hr-compliance-agent"],
		isLeaf: false,
		capabilities: ["orchestration", "task-delegation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "HR orchestrator — coordinates payroll and HR compliance specialists",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "fiscal-sunat-agent",
		name: "Fiscal SUNAT Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "fiscal-command-orchestrator",
		maySpawn: ["fiscal-sunat-payload-agent"],
		isLeaf: false,
		capabilities: ["sunat-validation", "compliance-audit", "document-processing"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "SUNAT specialist — validates invoices and tax submissions against SUNAT regulations",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "fiscal-sunat-payload-agent",
		name: "Fiscal SUNAT Payload Agent",
		system: "cli-delegation" as const,
		tier: "tier3b" as const,
		parentId: "fiscal-sunat-agent",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "document-processing"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "SUNAT payload drafter — prepares and formats SUNAT submission payloads",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "fiscal-ledger-agent",
		name: "Fiscal Ledger Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "fiscal-command-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["ledger-review", "compliance-audit"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Ledger specialist — reviews and validates ledger entries for fiscal compliance",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "fiscal-reconcile-agent",
		name: "Fiscal Reconcile Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "fiscal-command-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["bank-reconciliation", "data-sync"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Reconciliation specialist — matches bank transactions with ledger entries",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "hr-payroll-agent",
		name: "HR Payroll Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "drenyra-hr-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["hr-payroll", "integration"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Payroll specialist — processes payroll calculations and compliance",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "hr-compliance-agent",
		name: "HR Compliance Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "drenyra-hr-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["compliance-audit", "hr-payroll"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "HR compliance specialist — ensures HR operations meet regulatory requirements",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "swarm-codegen-agent",
		name: "Swarm Codegen Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "ai-swarm-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "test-generation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Codegen leaf — generates code scaffolding and boilerplate implementation",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "swarm-test-agent",
		name: "Swarm Test Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "ai-swarm-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["test-generation", "e2e-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Test leaf — generates and runs tests for code changes",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},
	{
		id: "swarm-review-agent",
		name: "Swarm Review Agent",
		system: "cli-delegation" as const,
		tier: "tier3" as const,
		parentId: "ai-swarm-orchestrator",
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "security-audit"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["cli"] as const,
		drenyraSubagent: null,
		description: "Review leaf — performs code review and security analysis",
		sourcePath: "apps/drenyra-cli/internal/delegation/graph.go",
	},

	// ═══════════════════════════════════════════════
	// Drenyra Core (packages/drenyra-core/src/types.ts)
	// ═══════════════════════════════════════════════
	{
		id: "eviden",
		name: "Eviden",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["evidence-tracking", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Eviden",
		description: "Evidence tracking agent — rastrea evidencia fiscal en comprobantes, SIRE, bancos y documentos",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "vigila",
		name: "Vigila",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["risk-analysis", "monitoring"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Vigila",
		description: "Risk monitoring agent — monitorea riesgo tributario, excepciones y umbrales de aprobación",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "traza",
		name: "Traza",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["tracing", "validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Traza",
		description: "Traceability agent — funde fuentes, reglas y razonamiento con TraceId para auditoría",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "regula",
		name: "Regula",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["compliance-audit", "sunat-validation"] as const,
		approvalClass: "financial-controller" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Regula",
		description: "Compliance agent — orquesta adaptación normativa por país mediante country packs",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "revela",
		name: "Revela",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["report-generation", "knowledge-retrieval"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Revela",
		description: "Explanation agent — explica decisiones y hallazgos en lenguaje claro",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "funde",
		name: "Funde",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["integration", "data-sync"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Funde",
		description: "Integration agent — sincroniza ERPs, bancos y fuentes documentales con controles de acceso",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "reporta",
		name: "Reporta",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["report-generation", "risk-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Reporta",
		description: "Prioritization agent — prioriza alertas y tareas críticas con contexto fiscal",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},
	{
		id: "archiva",
		name: "Archiva",
		system: "drenyra-core" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["evidence-tracking", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "workspace"] as const,
		drenyraSubagent: "Archiva",
		description: "Archive agent — consolida expediente auditable y evidencia versionada para fiscalización",
		sourcePath: "packages/drenyra-core/src/types.ts",
	},

	// ═══════════════════════════════════════════════
	// Domain Mock (packages/domain/src/drenyra/types.ts — AGENT_TYPES)
	// ═══════════════════════════════════════════════
	{
		id: "cpe-agent",
		name: "CPE Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["document-processing", "validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for CPE comprobante validation",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},
	{
		id: "sire-agent",
		name: "SIRE Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "compliance-audit"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for SIRE book review and validation",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},
	{
		id: "ledger-agent",
		name: "Ledger Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["ledger-review", "validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for ledger entry review",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},
	{
		id: "conciliation-agent",
		name: "Conciliation Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["bank-reconciliation", "data-sync"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for bank and ledger conciliation",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},
	{
		id: "fiscal-reviewer-agent",
		name: "Fiscal Reviewer Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["compliance-audit", "risk-analysis"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for fiscal review and risk assessment",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},
	{
		id: "evidence-agent",
		name: "Evidence Agent",
		system: "domain-mock" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["evidence-tracking", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Mock agent for evidence tracking and document linking",
		sourcePath: "packages/domain/src/drenyra/types.ts",
	},

	// ═══════════════════════════════════════════════
	// Agent Swarm (packages/agent-swarm/src/agents/)
	// ═══════════════════════════════════════════════
	// --- Financial Agents ---
	{
		id: "sunat-compliance-agent",
		name: "SUNAT Compliance Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "compliance-audit", "document-processing"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api", "batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Validates invoices and transactions against SUNAT 2026 regulations (IGV, RUC, UBL 2.1)",
		sourcePath: "packages/agent-swarm/src/agents/financial/sunat-compliance.agent.ts",
	},
	{
		id: "invoice-processor-agent",
		name: "Invoice Processor Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["invoice-processing", "document-processing", "validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Processes incoming invoices: extraction, validation, and ledger classification",
		sourcePath: "packages/agent-swarm/src/agents/financial/invoice-processor.agent.ts",
	},
	{
		id: "banking-reconciliation-agent",
		name: "Banking Reconciliation Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["bank-reconciliation", "data-sync", "integration"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api", "batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Matches bank statements against accounting entries for reconciliation",
		sourcePath: "packages/agent-swarm/src/agents/financial/banking-reconciliation.agent.ts",
	},
	{
		id: "tax-optimizer-agent",
		name: "Tax Optimizer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["compliance-audit", "risk-analysis", "report-generation"] as const,
		approvalClass: "financial-controller" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "Optimizes tax positions while maintaining SUNAT compliance",
		sourcePath: "packages/agent-swarm/src/agents/financial/tax-optimizer.agent.ts",
	},
	{
		id: "financial-analyzer-agent",
		name: "Financial Analyzer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["report-generation", "risk-analysis", "knowledge-retrieval"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web"] as const,
		drenyraSubagent: null,
		description: "Analyzes financial data and generates insights and forecasts",
		sourcePath: "packages/agent-swarm/src/agents/financial/financial-analyzer.agent.ts",
	},
	{
		id: "spot-calculator-agent",
		name: "SPOT Calculator Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "compliance-audit"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "Calculates SPOT (Sistema de Pago de Obligaciones Tributarias) detracciones",
		sourcePath: "packages/agent-swarm/src/agents/financial/spot-calculator.agent.ts",
	},

	// --- Code Review Agents ---
	{
		id: "security-audit-agent",
		name: "Security Audit Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["security-audit", "code-review"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Performs automated security audits on codebases and dependencies",
		sourcePath: "packages/agent-swarm/src/agents/code-review/security-audit.agent.ts",
	},
	{
		id: "quality-analyzer-agent",
		name: "Quality Analyzer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "performance-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Analyzes code quality metrics and enforces coding standards",
		sourcePath: "packages/agent-swarm/src/agents/code-review/quality-analyzer.agent.ts",
	},
	{
		id: "performance-analyzer-agent",
		name: "Performance Analyzer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["performance-analysis", "code-review"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Identifies performance bottlenecks and optimization opportunities",
		sourcePath: "packages/agent-swarm/src/agents/code-review/performance-analyzer.agent.ts",
	},
	{
		id: "style-checker-agent",
		name: "Style Checker Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "ui-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Enforces coding style consistency and formatting rules",
		sourcePath: "packages/agent-swarm/src/agents/code-review/style-checker.agent.ts",
	},

	// --- Development Agents ---
	{
		id: "code-generator-agent",
		name: "Code Generator Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "test-generation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "workspace"] as const,
		drenyraSubagent: null,
		description: "Generates code scaffolding, boilerplate, and implementation patterns",
		sourcePath: "packages/agent-swarm/src/agents/development/code-generator.agent.ts",
	},
	{
		id: "documentation-agent",
		name: "Documentation Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["report-generation", "knowledge-retrieval"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "web"] as const,
		drenyraSubagent: null,
		description: "Generates and maintains documentation, READMEs, and API references",
		sourcePath: "packages/agent-swarm/src/agents/development/documentation.agent.ts",
	},
	{
		id: "refactoring-agent",
		name: "Refactoring Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["migration", "code-review"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "workspace"] as const,
		drenyraSubagent: null,
		description: "Refactors code to improve structure, readability, and maintainability",
		sourcePath: "packages/agent-swarm/src/agents/development/refactoring.agent.ts",
	},
	{
		id: "migration-agent",
		name: "Migration Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["migration", "integration", "database-optimization"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "batch"] as const,
		drenyraSubagent: null,
		description: "Manages schema and data migrations across environments",
		sourcePath: "packages/agent-swarm/src/agents/development/migration.agent.ts",
	},
	{
		id: "feature-implementer-agent",
		name: "Feature Implementer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "test-generation", "integration"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "workspace"] as const,
		drenyraSubagent: null,
		description: "Implements new features based on requirements and specifications",
		sourcePath: "packages/agent-swarm/src/agents/development/feature-implementer.agent.ts",
	},
	{
		id: "bug-fixer-agent",
		name: "Bug Fixer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["code-review", "test-generation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "workspace"] as const,
		drenyraSubagent: null,
		description: "Analyzes and fixes bugs with regression test coverage",
		sourcePath: "packages/agent-swarm/src/agents/development/bug-fixer.agent.ts",
	},

	// --- Testing Agents ---
	{
		id: "test-generator-agent",
		name: "Test Generator Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["test-generation", "e2e-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Generates unit, integration, and E2E tests with coverage targets",
		sourcePath: "packages/agent-swarm/src/agents/testing/test-generator.agent.ts",
	},
	{
		id: "coverage-analyzer-agent",
		name: "Coverage Analyzer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["test-generation", "performance-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Analyzes test coverage gaps and suggests improvements",
		sourcePath: "packages/agent-swarm/src/agents/testing/coverage-analyzer.agent.ts",
	},
	{
		id: "integration-tester-agent",
		name: "Integration Tester Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["e2e-testing", "integration", "ui-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Tests API and service integrations end-to-end",
		sourcePath: "packages/agent-swarm/src/agents/testing/integration-tester.agent.ts",
	},
	{
		id: "e2e-tester-agent",
		name: "E2E Tester Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["e2e-testing", "ui-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Runs full end-to-end tests across the application stack",
		sourcePath: "packages/agent-swarm/src/agents/testing/e2e-tester.agent.ts",
	},

	// --- Infrastructure Agents ---
	{
		id: "database-optimizer-agent",
		name: "Database Optimizer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["database-optimization", "performance-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Optimizes database performance, indexes, and query execution",
		sourcePath: "packages/agent-swarm/src/agents/infrastructure/database-optimizer.agent.ts",
	},
	{
		id: "api-designer-agent",
		name: "API Designer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["api-design", "integration", "schema-validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "web"] as const,
		drenyraSubagent: null,
		description: "Designs RESTful and GraphQL API contracts and schemas",
		sourcePath: "packages/agent-swarm/src/agents/infrastructure/api-designer.agent.ts",
	},
	{
		id: "dependency-checker-agent",
		name: "Dependency Checker Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["dependency-checking", "security-audit"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Audits dependency trees for security vulnerabilities and outdated packages",
		sourcePath: "packages/agent-swarm/src/agents/infrastructure/dependency-checker.agent.ts",
	},
	{
		id: "schema-validator-agent",
		name: "Schema Validator Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["schema-validation", "validation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Validates data schemas against defined constraints and formats",
		sourcePath: "packages/agent-swarm/src/agents/infrastructure/schema-validator.agent.ts",
	},
	{
		id: "cost-optimizer-agent",
		name: "Cost Optimizer Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["cost-optimization", "performance-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Analyzes and optimizes cloud infrastructure costs",
		sourcePath: "packages/agent-swarm/src/agents/infrastructure/cost-optimizer.agent.ts",
	},

	// --- Workflow Agents ---
	{
		id: "deployment-agent",
		name: "Deployment Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["deployment", "integration", "monitoring"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "cli", "automation"] as const,
		drenyraSubagent: null,
		description: "Manages application deployment and release pipelines",
		sourcePath: "packages/agent-swarm/src/agents/workflow/deployment.agent.ts",
	},
	{
		id: "monitoring-agent",
		name: "Monitoring Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["monitoring", "notification", "performance-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Monitors system health, metrics, and alert thresholds",
		sourcePath: "packages/agent-swarm/src/agents/workflow/monitoring.agent.ts",
	},
	{
		id: "notification-agent",
		name: "Notification Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["notification", "approval-workflow"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Sends notifications across channels (email, Slack, in-app)",
		sourcePath: "packages/agent-swarm/src/agents/workflow/notification.agent.ts",
	},
	{
		id: "report-generator-agent",
		name: "Report Generator Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["report-generation", "data-visualization"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web", "batch"] as const,
		drenyraSubagent: null,
		description: "Generates customizable reports from business data",
		sourcePath: "packages/agent-swarm/src/agents/workflow/report-generator.agent.ts",
	},
	{
		id: "compliance-auditor-agent",
		name: "Compliance Auditor Agent",
		system: "agent-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["compliance-audit", "security-audit", "report-generation"] as const,
		approvalClass: "financial-controller" as const,
		supportedSurfaces: ["api", "batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Audits regulatory compliance across fiscal, data, and security domains",
		sourcePath: "packages/agent-swarm/src/agents/workflow/compliance-auditor.agent.ts",
	},

	// ═══════════════════════════════════════════════
	// API Drenyra Agents (apps/api/src/features/drenyra/agents.ts)
	// ═══════════════════════════════════════════════
	{
		id: "finance-agent",
		name: "Finance Agent",
		system: "api-agents" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["invoice-processing", "bank-reconciliation", "data-sync"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: "Funde",
		description: "Finance operations agent — integración financiera y sincronización",
		sourcePath: "apps/api/src/features/drenyra/agents.ts",
	},
	{
		id: "operations-agent",
		name: "Operations Agent",
		system: "api-agents" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["integration", "data-sync", "invoice-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: "Vigila",
		description: "Operations agent — ciclo operativo del negocio: clientes, proveedores, inventario",
		sourcePath: "apps/api/src/features/drenyra/agents.ts",
	},
	{
		id: "compliance-agent",
		name: "Compliance (Fiscal) Agent",
		system: "api-agents" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "compliance-audit", "document-processing"] as const,
		approvalClass: "financial-controller" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: "Regula",
		description: "Compliance agent — ciclo fiscal peruano: SUNAT, IGV, SIRE, CPE, cierre contable",
		sourcePath: "apps/api/src/features/drenyra/agents.ts",
	},
	{
		id: "system-admin-agent",
		name: "System Admin Agent",
		system: "api-agents" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["integration", "notification", "approval-workflow"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: "Archiva",
		description: "System administration agent — configuración del sistema, usuarios, integraciones",
		sourcePath: "apps/api/src/features/drenyra/agents.ts",
	},

	// ═══════════════════════════════════════════════
	// AI Pipeline (packages/ai/src/agents/)
	// ═══════════════════════════════════════════════
	{
		id: "reader-agent",
		name: "Reader Agent",
		system: "ai-pipeline" as const,
		tier: "tier3b" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["reading", "ocr", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "OCR multi-modal reader for invoice documents — Gemini Flash instance",
		sourcePath: "packages/ai/src/agents/agents/reader.agent.ts",
	},
	{
		id: "parser-agent",
		name: "Parser Agent",
		system: "ai-pipeline" as const,
		tier: "tier3b" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["parsing", "xml-parsing", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "XML UBL 2.0/2.1 parser and validator — Gemini Flash instance",
		sourcePath: "packages/ai/src/agents/agents/parser.agent.ts",
	},
	{
		id: "validator-agent",
		name: "Validator Agent",
		system: "ai-pipeline" as const,
		tier: "tier3b" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["validation", "sunat-validation", "compliance-audit"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "SUNAT 2026 compliance validator and XML generator — Grok adapter",
		sourcePath: "packages/ai/src/agents/agents/validator.agent.ts",
	},
	{
		id: "arbitrator-agent",
		name: "Arbitrator Agent",
		system: "ai-pipeline" as const,
		tier: "tier3b" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["arbitration", "knowledge-retrieval", "validation"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "Multi-agent debate arbitration and conflict resolution — Gemini Pro",
		sourcePath: "packages/ai/src/agents/agents/arbitrator.agent.ts",
	},

	// ═══════════════════════════════════════════════
	// AI Swarm (apps/api/src/features/ai-swarm/agents/)
	// ═══════════════════════════════════════════════
	{
		id: "swarm-evidence-agent",
		name: "Evidence Agent (AI Swarm)",
		system: "ai-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["evidence-tracking", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "Document storage and linking for audit trails — pure infrastructure, no LLM",
		sourcePath: "apps/api/src/features/ai-swarm/agents/evidence.agent.ts",
	},
	{
		id: "swarm-reconciliation-agent",
		name: "Reconciliation Agent (AI Swarm)",
		system: "ai-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["bank-reconciliation", "data-sync", "integration"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: null,
		description: "Bank statement matching with AI reasoning — handles partial payments and complex scenarios",
		sourcePath: "apps/api/src/features/ai-swarm/agents/reconciliation.agent.ts",
	},
	{
		id: "swarm-sunat-agent",
		name: "SUNAT Agent (AI Swarm)",
		system: "ai-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["sunat-validation", "compliance-audit", "validation"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: null,
		description: "Hybrid rule-based + AI SUNAT compliance validation (RUC, IGV, UBL 2.1, SIRE)",
		sourcePath: "apps/api/src/features/ai-swarm/agents/sunat.agent.ts",
	},
	{
		id: "swarm-pcge-agent",
		name: "PCGE Agent (AI Swarm)",
		system: "ai-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["ledger-review", "validation", "document-processing"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: null,
		description: "PCGE accounting classification — classifies transactions into Plan Contable General Empresarial accounts",
		sourcePath: "apps/api/src/features/ai-swarm/agents/pcge.agent.ts",
	},
	{
		id: "swarm-ocr-agent",
		name: "OCR Agent (AI Swarm)",
		system: "ai-swarm" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["ocr", "document-processing", "reading"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api"] as const,
		drenyraSubagent: null,
		description: "Document data extraction from PDF/image invoices using vision models",
		sourcePath: "apps/api/src/features/ai-swarm/agents/ocr.agent.ts",
	},

	// ═══════════════════════════════════════════════
	// SUNAT Visual Fallback (apps/api/src/features/cpe-validator/)
	// ═══════════════════════════════════════════════
	{
		id: "sunat-visual-fallback",
		name: "SUNAT Visual Fallback Subagent",
		system: "sunat-visual" as const,
		tier: "tier3b" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["visual-analysis", "sunat-validation"] as const,
		approvalClass: "supervisor" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "SUNAT visual fallback for CPE validation when primary SUNAT OSE is unreachable",
		sourcePath: "apps/api/src/features/cpe-validator/application/fallback/sunat-visual-subagent.ts",
	},

	// ═══════════════════════════════════════════════
	// ERP (agent-swarm additional categories)
	// ═══════════════════════════════════════════════
	{
		id: "anomaly-detector-agent",
		name: "Anomaly Detector Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["anomaly-detection", "risk-analysis"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch", "automation"] as const,
		drenyraSubagent: null,
		description: "Detects anomalous patterns in financial and operational data",
		sourcePath: "packages/agent-swarm/src/agents/ai-ml/anomaly-detector.agent.ts",
	},
	{
		id: "nlp-processor-agent",
		name: "NLP Processor Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["nlp-processing", "document-processing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "batch"] as const,
		drenyraSubagent: null,
		description: "Natural language processing for document understanding and classification",
		sourcePath: "packages/agent-swarm/src/agents/ai-ml/nlp-processor.agent.ts",
	},
	{
		id: "data-visualizer-agent",
		name: "Data Visualizer Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["data-visualization", "report-generation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web"] as const,
		drenyraSubagent: null,
		description: "Creates data visualizations and dashboards from business data",
		sourcePath: "packages/agent-swarm/src/agents/data-science/data-visualizer.agent.ts",
	},
	{
		id: "incident-responder-agent",
		name: "Incident Responder Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["incident-response", "monitoring", "notification"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Automated incident detection, triage, and response coordination",
		sourcePath: "packages/agent-swarm/src/agents/security-ops/incident-responder.agent.ts",
	},
	{
		id: "threat-detector-agent",
		name: "Threat Detector Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["threat-detection", "security-audit", "monitoring"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Proactive threat detection and vulnerability assessment",
		sourcePath: "packages/agent-swarm/src/agents/security-ops/threat-detector.agent.ts",
	},
	{
		id: "budget-tracker-agent",
		name: "Budget Tracker Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["budget-tracking", "cost-optimization", "report-generation"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "web"] as const,
		drenyraSubagent: null,
		description: "Tracks budgets, spending, and cost allocation across departments",
		sourcePath: "packages/agent-swarm/src/agents/cost-management/budget-tracker.agent.ts",
	},
	{
		id: "usability-tester-agent",
		name: "Usability Tester Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["usability-testing", "ui-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Evaluates user interfaces for usability and accessibility compliance",
		sourcePath: "packages/agent-swarm/src/agents/ux-ui/usability-tester.agent.ts",
	},
	{
		id: "accessibility-checker-agent",
		name: "Accessibility Checker Agent",
		system: "erp" as const,
		tier: "tier3" as const,
		parentId: null,
		maySpawn: [],
		isLeaf: true,
		capabilities: ["accessibility", "ui-testing", "usability-testing"] as const,
		approvalClass: "not-required" as const,
		supportedSurfaces: ["api", "automation"] as const,
		drenyraSubagent: null,
		description: "Audits web interfaces for WCAG compliance and accessibility issues",
		sourcePath: "packages/agent-swarm/src/agents/ux-ui/accessibility-checker.agent.ts",
	},

	// ═══════════════════════════════════════════════
	// Inbox Pipeline (packages/agent-swarm/src/agents/devops/ci-cd-pipeline + data-science/etl-pipeline)
	// ═══════════════════════════════════════════════

] as const satisfies readonly UnifiedAgentEntry[];

// Re-export types for convenience
export type { UnifiedAgentEntry };
export type { AgentCapability, ApprovalClass, SupportedSurface } from "./types";
export type { AgentTier, AgentSystem } from "./types";

/**
 * Find a single agent by its stable ID.
 *
 * @returns The matching entry, or `undefined` if not found.
 */
export function getAgentById(id: string): UnifiedAgentEntry | undefined {
	return AGENT_REGISTRY.find((a) => a.id === id);
}

/**
 * Return all agents belonging to a given system origin.
 */
export function getAgentsBySystem(system: AgentSystem): UnifiedAgentEntry[] {
	return AGENT_REGISTRY.filter((a) => a.system === system);
}

/**
 * Return all agents at a given tier level.
 */
export function getAgentsByTier(tier: AgentTier): UnifiedAgentEntry[] {
	return AGENT_REGISTRY.filter((a) => a.tier === tier);
}

/**
 * Return all leaf agents (isLeaf === true).
 */
export function getLeafAgents(): UnifiedAgentEntry[] {
	return AGENT_REGISTRY.filter((a) => a.isLeaf);
}

/**
 * Return all root/parent agents (parentId === null).
 */
export function getRootAgents(): UnifiedAgentEntry[] {
	return AGENT_REGISTRY.filter((a) => a.parentId === null);
}

/**
 * Return all agents that have a Drenyra subagent mapping.
 */
export function getDrenyraSubagents(): UnifiedAgentEntry[] {
	return AGENT_REGISTRY.filter((a) => a.drenyraSubagent !== null);
}
